using System.Globalization;
using System.Text.RegularExpressions;
using AcDream.Plugin.Abstractions;

namespace AcDream.Plugins.MossTank;

internal static class MetafSerializer
{
    private const string Comment = "~~";

    private static readonly string[] MetaHeaderLines =
    [
        "~~ {",
        "~~ FOR AUTO-COMPLETION ASSISTANCE: testvar getvar setvar touchvar clearallvars clearvar getcharintprop getchardoubleprop getcharquadprop getcharboolprop getcharstringprop getisspellknown getcancastspell_hunt getcancastspell_buff getcharvital_base getcharvital_current getcharvital_buffedmax getcharskill_traininglevel getcharskill_base getcharskill_buffed getplayerlandcell getplayercoordinates coordinategetns coordinategetwe coordinategetz coordinatetostring coordinateparse coordinatedistancewithz coordinatedistanceflat wobjectgetphysicscoordinates wobjectgetname wobjectgetobjectclass wobjectgettemplatetype wobjectgetisdooropen wobjectfindnearestmonster wobjectfindnearestdoor wobjectfindnearestbyobjectclass wobjectfindininventorybytemplatetype wobjectfindininventorybyname wobjectfindininventorybynamerx wobjectgetselection wobjectgetplayer wobjectfindnearestbynameandobjectclass actiontryselect actiontryuseitem actiontryapplyitem actiontrygiveitem actiontryequipanywand actiontrycastbyid actiontrycastbyidontarget chatbox chatboxpaste statushud statushudcolored uigetcontrol uisetlabel isfalse istrue iif randint cstr strlen getobjectinternaltype cstrf stopwatchcreate stopwatchstart stopwatchstop stopwatchelapsedseconds cnumber floor ceiling round abs getworldname getitemcountininventorybyname getheading getitemcountininventorybynamerx getheadingto actiontrygiveprofile vitae getfellowshipstatus getfellowshipname getfellowshipisopen getfellowshipisleader getfellowshipleaderid getfellowshipcanrecruit getfellowid getfellowshipcount getfellowshiplocked getfellowname getfellowshipisfull sin cos tan sqrt asin acos atan atan2 sinh cosh tanh vtsetmetastate getregexmatch echo chr ord wobjectgetid wobjectgethealth wobjectfindbyid wobjectgetintprop wobjectfindnearestbytemplatetype wobjectgetopencontainer testquestflag getquestktprogress isrefreshingquests getquestktrequired getqueststatus getisday getgamehour getgamehourname getisnight getgameday getgameticks getminutesuntilday getgamemonth getgamemonthname getminutesuntilnight getgameyear uisetvisible uiviewvisible uiviewexists getgvar touchgvar getpvar touchpvar setgvar cleargvar setpvar clearpvar testgvar clearallgvars testpvar clearallpvars dictgetitem dictcreate dicthaskey dictadditem dictkeys dictremovekey dictvalues dictclear dictsize dictcopy listgetitem listpop listcreate listcontains listremove listadd listindexof listremoveat listinsert listlastindexof listclear listcopy listcount listreverse",
        "",
        "~~\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ File auto-generated by metaf, a program created by Eskarina of Morningthaw/Coldeve.\t",
        "~~\t\tGet metaf here: https://github.com/JJEII/metaf/\t\t\t\t\t\t\t\t\t",
        "~~\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ All recognized structural designators:\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tSTATE:\t\t\t\tDO:\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tIF:\t\t\t\t\tNAV:\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ All recognized CONDITION (IF:) operation keywords:\t\t\t\t\t\t\t\t\t",
        "~~\t\tNever\t\t\t\tNavEmpty\t\t\tMobsInDist_Priority\t\tNot\t\t\t\t",
        "~~\t\tAlways\t\t\t\tDeath\t\t\t\tNeedToBuff\t\t\t\tPSecsInStateGE\t",
        "~~\t\tAll\t\t\t\t\tVendorOpen\t\t\tNoMobsInDist\t\t\tSecsOnSpellGE\t",
        "~~\t\tAny\t\t\t\t\tVendorClosed\t\tBlockE\t\t\t\t\tBuPercentGE\t\t",
        "~~\t\tChatMatch\t\t\tItemCountLE\t\t\tCellE\t\t\t\t\tDistToRteGE\t\t",
        "~~\t\tMainSlotsLE\t\t\tItemCountGE\t\t\tIntoPortal\t\t\t\tExpr\t\t\t",
        "~~\t\tSecsInStateGE\t\tMobsInDist_Name\t\tExitPortal\t\t\t\tChatCapture\t\t",
        "~~\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ All recognized ACTION (DO:) operation keywords:\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tNone\t\t\t\tEmbedNav\t\t\tChatExpr\t\t\t\tSetOpt\t\t\t",
        "~~\t\tSetState\t\t\tCallState\t\t\tSetWatchdog\t\t\t\tCreateView\t\t",
        "~~\t\tChat\t\t\t\tReturn\t\t\t\tClearWatchdog\t\t\tDestroyView\t\t",
        "~~\t\tDoAll\t\t\t\tDoExpr\t\t\t\tGetOpt\t\t\t\t\tDestroyAllViews\t",
        "~~\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ All recognized NAV types:\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tcircular\t\t\tfollow\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tlinear\t\t\t\tonce\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ All recognized NAV NODE types:\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tflw\t\t\t\t\tvnd\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tpnt\t\t\t\t\tptl\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\trcl\t\t\t\t\ttlk\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tpau\t\t\t\t\tchk\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tcht\t\t\t\t\tjmp\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tprt (deprecated in VTank)\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ }\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
    ];
    private static readonly string MetaHeader = string.Join("\n", MetaHeaderLines) + "\n";

    private static readonly string[] NavOutputHeaderLines =
    [
        "~~ {",
        "~~ FOR AUTO-COMPLETION ASSISTANCE: testvar getvar setvar touchvar clearallvars clearvar getcharintprop getchardoubleprop getcharquadprop getcharboolprop getcharstringprop getisspellknown getcancastspell_hunt getcancastspell_buff getcharvital_base getcharvital_current getcharvital_buffedmax getcharskill_traininglevel getcharskill_base getcharskill_buffed getplayerlandcell getplayercoordinates coordinategetns coordinategetwe coordinategetz coordinatetostring coordinateparse coordinatedistancewithz coordinatedistanceflat wobjectgetphysicscoordinates wobjectgetname wobjectgetobjectclass wobjectgettemplatetype wobjectgetisdooropen wobjectfindnearestmonster wobjectfindnearestdoor wobjectfindnearestbyobjectclass wobjectfindininventorybytemplatetype wobjectfindininventorybyname wobjectfindininventorybynamerx wobjectgetselection wobjectgetplayer wobjectfindnearestbynameandobjectclass actiontryselect actiontryuseitem actiontryapplyitem actiontrygiveitem actiontryequipanywand actiontrycastbyid actiontrycastbyidontarget chatbox chatboxpaste statushud statushudcolored uigetcontrol uisetlabel isfalse istrue iif randint cstr strlen getobjectinternaltype cstrf stopwatchcreate stopwatchstart stopwatchstop stopwatchelapsedseconds cnumber floor ceiling round abs getworldname getitemcountininventorybyname getheading getitemcountininventorybynamerx getheadingto actiontrygiveprofile vitae getfellowshipstatus getfellowshipname getfellowshipisopen getfellowshipisleader getfellowshipleaderid getfellowshipcanrecruit getfellowid getfellowshipcount getfellowshiplocked getfellowname getfellowshipisfull sin cos tan sqrt asin acos atan atan2 sinh cosh tanh vtsetmetastate getregexmatch echo chr ord wobjectgetid wobjectgethealth wobjectfindbyid wobjectgetintprop wobjectfindnearestbytemplatetype wobjectgetopencontainer testquestflag getquestktprogress isrefreshingquests getquestktrequired getqueststatus getisday getgamehour getgamehourname getisnight getgameday getgameticks getminutesuntilday getgamemonth getgamemonthname getminutesuntilnight getgameyear uisetvisible uiviewvisible uiviewexists getgvar touchgvar getpvar touchpvar setgvar cleargvar setpvar clearpvar testgvar clearallgvars testpvar clearallpvars dictgetitem dictcreate dicthaskey dictadditem dictkeys dictremovekey dictvalues dictclear dictsize dictcopy listgetitem listpop listcreate listcontains listremove listadd listindexof listremoveat listinsert listlastindexof listclear listcopy listcount listreverse",
        "",
        "~~\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ File auto-generated by metaf, a program created by Eskarina of Morningthaw/Coldeve.\t",
        "~~\t\tGet metaf here: https://github.com/JJEII/metaf/\t\t\t\t\t\t\t\t\t",
        "~~\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ All recognized structural designators in a NAV-ONLY file:\t\t\t\t\t\t\t",
        "~~\t\tNAV:\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ All recognized NAV types:\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tcircular\t\t\tfollow\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tlinear\t\t\t\tonce\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ All recognized NAV NODE types:\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tflw\t\t\t\t\tvnd\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tpnt\t\t\t\t\tptl\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\trcl\t\t\t\t\ttlk\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tpau\t\t\t\t\tchk\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tcht\t\t\t\t\tjmp\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~\t\tprt (deprecated in VTank)\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "",
        "~~ \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
        "~~ \t\t\t\tREMEMBER THAT NAV-ONLY FILES MUST CONTAIN EXACTLY ONE NAV!\t\t\t\t",
        "~~ }\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
    ];
    private static readonly string NavOutputHeader = string.Join("\n", NavOutputHeaderLines) + "\n";

    // ------------------------------------------------------------------
    // Grammar building blocks (rx._D/_I/_H/_S/_L, metaf_monolithic.py:172-176)
    // ------------------------------------------------------------------
    private const string D = @"[+\-]?(([1-9][0-9]*\.|[0-9]?\.)([0-9]+([eE][+\-]?[0-9]+)|[0-9]+)|([1-9][0-9]*|0))";
    private const string I = @"[+\-]?([1-9][0-9]*|0)";
    private const string H = @"[A-F0-9]{8}";
    private const string S = @"[{]([^{}]|\{\{|\})*[}]";

    private static readonly Regex TrailingComment = new(
        @"\s*(~~.*)?$", RegexOptions.Compiled);
    private static readonly Regex BlankOrCommentLine = new(
        @"^\s*(~~.*)?$", RegexOptions.Compiled);
    private static readonly Regex LeadIn = new(
        @"^(?<tabs>[\t]*)(?<type>STATE:|IF:|DO:|NAV:)", RegexOptions.Compiled);
    private static readonly Regex AnyConditionOp = new(
        @"^(?<tabs>[\t]*)\s*(?<op>Never|Always|All|Any|ChatMatch|MainSlotsLE|SecsInStateGE|NavEmpty|Death|VendorOpen|VendorClosed|ItemCountLE|ItemCountGE|MobsInDist_Name|MobsInDist_Priority|NeedToBuff|NoMobsInDist|BlockE|CellE|IntoPortal|ExitPortal|Not|PSecsInStateGE|SecsOnSpellGE|BuPercentGE|DistToRteGE|Expr|ChatCapture)",
        RegexOptions.Compiled);
    private static readonly Regex AnyActionOp = new(
        @"^(?<tabs>[\t]*)\s*(?<op>None|SetState|DoAll|EmbedNav|CallState|Return|DoExpr|ChatExpr|Chat|SetWatchdog|ClearWatchdog|GetOpt|SetOpt|CreateView|DestroyView|DestroyAllViews)",
        RegexOptions.Compiled);
    private static readonly Regex AnyNavNodeType = new(
        @"^\t(?<type>flw|pnt|prt|rcl|pau|cht|vnd|ptl|tlk|chk|jmp)", RegexOptions.Compiled);
    private static readonly Regex NavHeader = new(
        @"^\s+(?<l>[a-zA-Z_][a-zA-Z0-9_]*)\s+(?<l2>circular|linear|once|follow)$",
        RegexOptions.Compiled);
    private static readonly Regex EmptyArgs = new(@"^$", RegexOptions.Compiled);
    private static readonly Regex XfArgs = new(
        $@"^\s*(?<a>{D})\s+(?<b>{D})\s+(?<c>{D})\s+(?<d>{D})\s+(?<e>{D})\s+(?<f>{D})\s+(?<g>{D})\s*$",
        RegexOptions.Compiled);

    private static readonly Dictionary<string, Regex> ConditionArgs = new()
    {
        ["Never"] = EmptyArgs,
        ["Always"] = EmptyArgs,
        ["All"] = EmptyArgs,
        ["Any"] = EmptyArgs,
        ["ChatMatch"] = new($@"^\s+(?<s>{S})$", RegexOptions.Compiled),
        ["MainSlotsLE"] = new($@"^\s+(?<i>{I})$", RegexOptions.Compiled),
        ["SecsInStateGE"] = new($@"^\s+(?<i>{I})$", RegexOptions.Compiled),
        ["NavEmpty"] = EmptyArgs,
        ["Death"] = EmptyArgs,
        ["VendorOpen"] = EmptyArgs,
        ["VendorClosed"] = EmptyArgs,
        ["ItemCountLE"] = new($@"^\s+(?<i>{I})\s+(?<s>{S})$", RegexOptions.Compiled),
        ["ItemCountGE"] = new($@"^\s+(?<i>{I})\s+(?<s>{S})$", RegexOptions.Compiled),
        ["MobsInDist_Name"] = new($@"^\s+(?<i>{I})\s+(?<d>{D})\s+(?<s>{S})$", RegexOptions.Compiled),
        ["MobsInDist_Priority"] = new($@"^\s+(?<i>{I})\s+(?<d>{D})\s+(?<i2>{I})$", RegexOptions.Compiled),
        ["NeedToBuff"] = EmptyArgs,
        ["NoMobsInDist"] = new($@"^\s+(?<d>{D})$", RegexOptions.Compiled),
        ["BlockE"] = new($@"^\s+(?<h>{H})$", RegexOptions.Compiled),
        ["CellE"] = new($@"^\s+(?<h>{H})$", RegexOptions.Compiled),
        ["IntoPortal"] = EmptyArgs,
        ["ExitPortal"] = EmptyArgs,
        ["Not"] = EmptyArgs,
        ["PSecsInStateGE"] = new($@"^\s+(?<i>{I})$", RegexOptions.Compiled),
        ["SecsOnSpellGE"] = new($@"^\s+(?<i>{I})\s+(?<i2>{I})$", RegexOptions.Compiled),
        ["BuPercentGE"] = new($@"^\s+(?<i>{I})$", RegexOptions.Compiled),
        ["DistToRteGE"] = new($@"^\s+(?<d>{D})$", RegexOptions.Compiled),
        ["Expr"] = new($@"^\s+(?<s>{S})$", RegexOptions.Compiled),
        ["ChatCapture"] = new($@"^\s+(?<s>{S})\s+(?<s2>{S})$", RegexOptions.Compiled),
    };

    private static readonly Dictionary<string, Regex> ActionArgs = new()
    {
        ["None"] = EmptyArgs,
        ["SetState"] = new($@"^\s+(?<s>{S})$", RegexOptions.Compiled),
        ["Chat"] = new($@"^\s+(?<s>{S})$", RegexOptions.Compiled),
        ["DoAll"] = EmptyArgs,
        ["EmbedNav"] = new(
            $@"^\s+(?<l>[a-zA-Z_][a-zA-Z0-9_]*)\s+(?<s>{S})(\s+(?<xf>{S}))?$",
            RegexOptions.Compiled),
        ["CallState"] = new($@"^\s+(?<s>{S})\s+(?<s2>{S})$", RegexOptions.Compiled),
        ["Return"] = EmptyArgs,
        ["DoExpr"] = new($@"^\s+(?<s>{S})$", RegexOptions.Compiled),
        ["ChatExpr"] = new($@"^\s+(?<s>{S})$", RegexOptions.Compiled),
        ["SetWatchdog"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<s>{S})$", RegexOptions.Compiled),
        ["ClearWatchdog"] = EmptyArgs,
        ["GetOpt"] = new($@"^\s+(?<s>{S})\s+(?<s2>{S})$", RegexOptions.Compiled),
        ["SetOpt"] = new($@"^\s+(?<s>{S})\s+(?<s2>{S})$", RegexOptions.Compiled),
        ["CreateView"] = new($@"^\s+(?<s>{S})\s+(?<s2>{S})$", RegexOptions.Compiled),
        ["DestroyView"] = new($@"^\s+(?<s>{S})$", RegexOptions.Compiled),
        ["DestroyAllViews"] = EmptyArgs,
    };

    private static readonly Dictionary<string, Regex> NavArgs = new()
    {
        ["flw"] = new($@"^\s+(?<h>{H})\s+(?<s>{S})$", RegexOptions.Compiled),
        ["pnt"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<d3>{D})$", RegexOptions.Compiled),
        ["prt"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<d3>{D})\s+(?<h>{H})$", RegexOptions.Compiled),
        ["rcl"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<d3>{D})\s+(?<s>{S})$", RegexOptions.Compiled),
        ["pau"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<d3>{D})\s+(?<d4>{D})$", RegexOptions.Compiled),
        ["cht"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<d3>{D})\s+(?<s>{S})$", RegexOptions.Compiled),
        ["vnd"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<d3>{D})\s+(?<h>{H})\s+(?<s>{S})$", RegexOptions.Compiled),
        ["ptl"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<d3>{D})\s+(?<d4>{D})\s+(?<d5>{D})\s+(?<d6>{D})\s+(?<i>{I})\s+(?<s>{S})$", RegexOptions.Compiled),
        ["tlk"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<d3>{D})\s+(?<d4>{D})\s+(?<d5>{D})\s+(?<d6>{D})\s+(?<i>{I})\s+(?<s>{S})$", RegexOptions.Compiled),
        ["chk"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<d3>{D})$", RegexOptions.Compiled),
        ["jmp"] = new($@"^\s+(?<d>{D})\s+(?<d2>{D})\s+(?<d3>{D})\s+(?<d4>{D})\s+(?<s>{S})\s+(?<d5>{D})$", RegexOptions.Compiled),
    };

    private const int ConditionDepth = 2;
    private const int ActionDepth = 3;

    private sealed class Cursor(string[] lines)
    {
        public string[] Lines { get; } = lines;
        public int L { get; set; }
        public int C { get; set; }

        public FormatException Error(string message) =>
            new($"line {Math.Min(L + 1, Lines.Length)}: {message}");

        public void SkipBlank()
        {
            while (L < Lines.Length && BlankOrCommentLine.IsMatch(Lines[L]))
                L++;
        }

        public string RemainderOfCurrentLine() => TrailingComment.Replace(
            Lines[L][Math.Min(C, Lines[L].Length)..], string.Empty);
    }

    // ==================================================================
    // Meta (STATE:/IF:/DO:/NAV: — a full profile, embedded navs included).
    // ==================================================================

    public static bool TryLoadMeta(
        string text,
        ISpellCatalog spells,
        out MetaProfile profile,
        out string error)
    {
        ArgumentNullException.ThrowIfNull(spells);
        try
        {
            var cursor = new Cursor(SplitLines(text));
            var embeddedNavs = new Dictionary<string, (string NavType, List<RouteWaypoint> Nodes,
                uint FollowTargetId, string FollowTargetName)>(StringComparer.Ordinal);
            var parsed = new MetaProfile();
            bool sawState = false;
            bool sawNav = false;
            cursor.SkipBlank();
            while (cursor.L < cursor.Lines.Length)
            {
                Match lead = LeadIn.Match(cursor.Lines[cursor.L]);
                if (!lead.Success)
                    throw cursor.Error("expected 'STATE:' or 'NAV:'.");
                if (lead.Groups["type"].Value == "NAV:")
                {
                    sawNav = true;
                    ReadNavBlock(cursor, embeddedNavs, spells);
                    continue;
                }
                if (lead.Groups["type"].Value != "STATE:")
                    throw cursor.Error("expected 'STATE:' or 'NAV:'.");
                sawState = true;
                ReadState(cursor, parsed);
            }
            if (sawNav && !sawState)
            {
                throw cursor.Error(
                    "contains only NAV: block(s) and no STATE: block — this looks like "
                    + "a stand-alone route profile that belongs in the navs/ folder, "
                    + "not a Meta profile.");
            }
            // Second pass: EmbedNav actions reference navs that may be defined
            // anywhere in the file (metaf allows forward references — a NAV:
            // block can appear before or after the STATE that embeds it).
            ResolveEmbeddedNavs(parsed, embeddedNavs);
            profile = parsed;
            error = string.Empty;
            return true;
        }
        catch (Exception exception) when (exception is FormatException or RegexMatchTimeoutException)
        {
            profile = new MetaProfile();
            error = exception.Message;
            return false;
        }
    }

    public static string SaveMeta(MetaProfile profile) =>
        SaveMeta(profile, dropDisabledRules: false);

    public static string SaveMeta(MetaProfile profile, bool dropDisabledRules)
    {
        ArgumentNullException.ThrowIfNull(profile);
        if (!dropDisabledRules)
        {
            int disabledCount = profile.Rules.Count(static rule => !rule.Enabled);
            if (disabledCount > 0)
            {
                throw new InvalidOperationException(
                    $"SaveMeta: {disabledCount} disabled rule(s) have no metaf-compatible "
                    + "representation and would be silently dropped. Call "
                    + "SaveMeta(profile, dropDisabledRules: true) to accept that loss "
                    + "explicitly.");
            }
        }
        var lines = new List<string> { MetaHeader };
        var embedTags = new Dictionary<MetaAction, string>(ReferenceEqualityComparer.Instance);
        var embedOrder = new List<(MetaAction Action, string Tag)>();
        int embedCounter = 0;
        foreach (MetaRule rule in profile.Rules.Where(static rule => rule.Enabled))
            AssignEmbedTags(rule.Action, embedTags, embedOrder, ref embedCounter);

        foreach (IGrouping<string, MetaRule> stateGroup in profile.Rules
            .Where(static rule => rule.Enabled)
            .GroupBy(static rule => rule.State, StringComparer.Ordinal))
        {
            lines.Add($"STATE: {{{stateGroup.Key}}} ~~ {{");
            foreach (MetaRule rule in stateGroup)
            {
                WriteCondition(lines, rule.Condition, "IF:", 1, ConditionDepth);
                WriteAction(lines, rule.Action, "DO:", 2, ActionDepth, embedTags);
            }
            lines.Add("~~ }");
        }
        if (embedOrder.Count > 0)
        {
            // Meta.ExportToMetAF (metaf_monolithic.py:12784-12790): a blank
            // line, this exact separator (no space either side of the "~~"
            // delimiters), then another blank line, before any NAV: block.
            lines.Add(string.Empty);
            lines.Add("~~========================= ONLY NAVS APPEAR BELOW THIS LINE =========================~~");
            lines.Add(string.Empty);
        }
        foreach ((MetaAction action, string tag) in embedOrder)
        {
            if (action.EmbeddedRoute is { } nav)
                WriteNavBlock(lines, tag, nav);
        }
        return string.Join("\r\n", lines) + "\r\n";
    }

    private static readonly Regex NonTagCharacter = new(@"[^a-zA-Z0-9_]", RegexOptions.Compiled);

    private static void AssignEmbedTags(
        MetaAction action,
        Dictionary<MetaAction, string> tags,
        List<(MetaAction Action, string Tag)> order,
        ref int counter)
    {
        if (action.Kind == MetaActionKind.LoadEmbeddedNavigationRoute)
        {
            string sanitized = NonTagCharacter.Replace(action.SecondaryText ?? string.Empty, "_");
            string postfix = sanitized.Length > 0 ? $"__{sanitized}" : string.Empty;
            string tag = $"nav{counter}{postfix}";
            tags[action] = tag;
            order.Add((action, tag));
            counter++;
        }
        foreach (MetaAction child in action.Children)
            AssignEmbedTags(child, tags, order, ref counter);
    }

    /// <summary>Internal (not private) so other one-shot import readers can share this no-op.</summary>
    internal sealed class NoOpSpells : ISpellCatalog
    {
        public static NoOpSpells Instance { get; } = new();
        public IReadOnlyList<PluginSpellInfo> KnownSelfBuffs => [];
        public bool TryGet(uint spellId, out PluginSpellInfo info)
        {
            info = default;
            return false;
        }
    }

    // ------------------------------------------------------------------
    // STATE / Rule (IF:/DO:) reading — State.ImportFromMetAF, Rule.ImportFromMetAF.
    // ------------------------------------------------------------------

    private static void ReadState(Cursor cursor, MetaProfile profile)
    {
        Match header = LeadIn.Match(cursor.Lines[cursor.L]);
        string headerRemainder = TrailingComment.Replace(
            cursor.Lines[cursor.L][(header.Groups["tabs"].Length + "STATE:".Length)..],
            string.Empty);
        Match name = Regex.Match(headerRemainder, $@"^\s+(?<s>{S})$");
        if (!name.Success)
            throw cursor.Error("'STATE:' must be followed by a delimited string name.");
        string stateName = StripDelimiters(name.Groups["s"].Value);
        cursor.L++;

        int rulesRead = 0;
        cursor.SkipBlank();
        while (cursor.L < cursor.Lines.Length)
        {
            Match lead = LeadIn.Match(cursor.Lines[cursor.L]);
            if (!lead.Success)
                throw cursor.Error("expected 'STATE:', 'IF:', or 'NAV:'.");
            if (lead.Groups["type"].Value is "STATE:" or "NAV:")
                break;
            if (lead.Groups["type"].Value != "IF:")
                throw cursor.Error("expected an 'IF:' line to start a new Rule.");

            cursor.C = 0;
            MetaCondition condition = ReadTopLevelCondition(cursor);
            MetaAction action = ReadTopLevelAction(cursor);
            profile.Rules.Add(new MetaRule
            {
                State = stateName,
                Condition = condition,
                Action = action,
                Enabled = true,
            });
            rulesRead++;
            cursor.SkipBlank();
        }
        if (rulesRead == 0)
            throw cursor.Error($"state '{stateName}' has no rules (every state needs at least one).");
    }

    private static MetaCondition ReadTopLevelCondition(Cursor cursor)
    {
        cursor.SkipBlank();
        Match lead = LeadIn.Match(cursor.Lines[cursor.L]);
        if (!lead.Success || lead.Groups["type"].Value != "IF:")
            throw cursor.Error("expected an 'IF:' line.");
        cursor.C = lead.Length;
        Match op = AnyConditionOp.Match(cursor.Lines[cursor.L][cursor.C..]);
        if (!op.Success)
            throw cursor.Error("expected a Condition operation after 'IF:'.");
        cursor.C += op.Groups["op"].Index + op.Groups["op"].Length;
        return ReadCondition(cursor, op.Groups["op"].Value, ConditionDepth);
    }

    private static MetaAction ReadTopLevelAction(Cursor cursor)
    {
        cursor.SkipBlank();
        Match lead = LeadIn.Match(cursor.Lines[cursor.L]);
        if (!lead.Success || lead.Groups["type"].Value != "DO:")
            throw cursor.Error("expected a 'DO:' line.");
        cursor.C = lead.Length;
        Match op = AnyActionOp.Match(cursor.Lines[cursor.L][cursor.C..]);
        if (!op.Success)
            throw cursor.Error("expected an Action operation after 'DO:'.");
        cursor.C += op.Groups["op"].Index + op.Groups["op"].Length;
        return ReadAction(cursor, op.Groups["op"].Value, ActionDepth);
    }


    private static MetaCondition ReadCondition(Cursor cursor, string keyword, int depth)
    {
        if (keyword == "Not")
        {
            var not = new MetaCondition { Kind = MetaConditionKind.Not };
            string notRemainder = cursor.Lines[cursor.L][cursor.C..];
            Match nested = AnyConditionOp.Match(notRemainder);
            if (!nested.Success)
                throw cursor.Error("'Not' must be followed by a Condition operation on the same line.");
            cursor.C += nested.Groups["op"].Index + nested.Groups["op"].Length;
            not.Children.Add(ReadCondition(cursor, nested.Groups["op"].Value, depth));
            return not;
        }

        var value = new MetaCondition { Kind = ConditionKind(keyword) };
        string remainder = cursor.RemainderOfCurrentLine();
        cursor.L++;
        Regex argRegex = ConditionArgs[keyword];
        Match args = argRegex.Match(remainder);
        if (!args.Success)
            throw cursor.Error($"'{keyword}' arguments do not match the expected shape.");

        switch (keyword)
        {
            case "ChatMatch":
                value.Text = StripDelimiters(args.Groups["s"].Value);
                break;
            case "MainSlotsLE" or "SecsInStateGE" or "PSecsInStateGE" or "BuPercentGE":
                value.Number = ParseInt(args.Groups["i"].Value);
                break;
            case "ItemCountLE" or "ItemCountGE":
                value.Number = ParseInt(args.Groups["i"].Value);
                value.Text = StripDelimiters(args.Groups["s"].Value);
                break;
            case "MobsInDist_Name":
                value.Number = ParseInt(args.Groups["i"].Value);
                value.SecondaryNumber = ParseDouble(args.Groups["d"].Value);
                value.Text = StripDelimiters(args.Groups["s"].Value);
                break;
            case "MobsInDist_Priority":
                value.Number = ParseInt(args.Groups["i"].Value);
                value.SecondaryNumber = ParseDouble(args.Groups["d"].Value);
                value.TertiaryNumber = ParseInt(args.Groups["i2"].Value);
                break;
            case "NoMobsInDist" or "DistToRteGE":
                value.Number = ParseDouble(args.Groups["d"].Value);
                break;
            case "BlockE" or "CellE":
                value.Number = ParseHexAsInt(args.Groups["h"].Value);
                break;
            case "SecsOnSpellGE":
                value.SecondaryNumber = ParseInt(args.Groups["i"].Value);
                value.Number = ParseInt(args.Groups["i2"].Value);
                break;
            case "Expr":
                value.Text = StripDelimiters(args.Groups["s"].Value);
                break;
            case "ChatCapture":
                value.Text = StripDelimiters(args.Groups["s"].Value);
                value.SecondaryText = StripDelimiters(args.Groups["s2"].Value);
                break;
            case "All" or "Any":
                ReadNestedConditions(cursor, value, depth);
                break;
        }
        return value;
    }

    private static void ReadNestedConditions(Cursor cursor, MetaCondition parent, int depth)
    {
        while (true)
        {
            cursor.SkipBlank();
            if (cursor.L >= cursor.Lines.Length)
                throw cursor.Error("hit end-of-file inside an All/Any condition.");
            Match lead = LeadIn.Match(cursor.Lines[cursor.L]);
            if (lead.Success)
            {
                if (lead.Groups["type"].Value == "DO:")
                    return;
                throw cursor.Error("missing 'DO:' to close this Rule.");
            }
            Match op = AnyConditionOp.Match(cursor.Lines[cursor.L]);
            if (!op.Success)
                throw cursor.Error("expected a Condition operation or 'DO:'.");
            int tabs = op.Groups["tabs"].Length;
            if (tabs <= ConditionDepth)
                throw cursor.Error("not tabbed in enough to be inside an All/Any condition.");
            if (tabs <= depth)
                return; // this line belongs to an ancestor All/Any, not us.
            if (tabs > depth + 1)
                throw cursor.Error("tabbed in too far inside an All/Any condition.");
            cursor.C = op.Groups["op"].Index + op.Groups["op"].Length;
            parent.Children.Add(ReadCondition(cursor, op.Groups["op"].Value, depth + 1));
        }
    }


    private static MetaAction ReadAction(Cursor cursor, string keyword, int depth)
    {
        var value = new MetaAction { Kind = ActionKind(keyword) };
        string remainder = cursor.RemainderOfCurrentLine();
        cursor.L++;
        Regex argRegex = ActionArgs[keyword];
        Match args = argRegex.Match(remainder);
        if (!args.Success)
            throw cursor.Error($"'{keyword}' arguments do not match the expected shape.");

        switch (keyword)
        {
            case "SetState" or "Chat" or "DoExpr" or "ChatExpr":
                value.Text = StripDelimiters(args.Groups["s"].Value);
                break;
            case "CallState":
                value.Text = StripDelimiters(args.Groups["s"].Value);
                value.SecondaryText = StripDelimiters(args.Groups["s2"].Value);
                break;
            case "SetWatchdog":
                value.Number = ParseDouble(args.Groups["d"].Value);
                value.SecondaryNumber = ParseDouble(args.Groups["d2"].Value);
                value.Text = StripDelimiters(args.Groups["s"].Value);
                break;
            case "GetOpt" or "SetOpt" or "CreateView":
                value.Text = StripDelimiters(args.Groups["s"].Value);
                value.SecondaryText = StripDelimiters(args.Groups["s2"].Value);
                break;
            case "DestroyView":
                value.Text = StripDelimiters(args.Groups["s"].Value);
                break;
            case "EmbedNav":
                value.SecondaryText = args.Groups["l"].Value; // tag
                value.Text = StripDelimiters(args.Groups["s"].Value); // display name (temp)
                break;
            case "DoAll":
                ReadNestedActions(cursor, value, depth);
                break;
        }
        return value;
    }

    private static void ReadNestedActions(Cursor cursor, MetaAction parent, int depth)
    {
        while (true)
        {
            cursor.SkipBlank();
            if (cursor.L >= cursor.Lines.Length)
                return; // DoAll may legally be the last thing in the file.
            Match lead = LeadIn.Match(cursor.Lines[cursor.L]);
            if (lead.Success)
                return; // STATE:/IF:/DO:/NAV: all end this DoAll.
            Match op = AnyActionOp.Match(cursor.Lines[cursor.L]);
            if (!op.Success)
                throw cursor.Error("expected an Action operation.");
            int tabs = op.Groups["tabs"].Length;
            if (tabs <= ActionDepth)
                throw cursor.Error("not tabbed in enough to be inside a DoAll action.");
            if (tabs <= depth)
                return;
            if (tabs > depth + 1)
                throw cursor.Error("tabbed in too far inside a DoAll action.");
            cursor.C = op.Groups["op"].Index + op.Groups["op"].Length;
            parent.Children.Add(ReadAction(cursor, op.Groups["op"].Value, depth + 1));
        }
    }

    private static void ResolveEmbeddedNavs(
        MetaProfile profile,
        IReadOnlyDictionary<string, (string NavType, List<RouteWaypoint> Nodes, uint FollowTargetId, string FollowTargetName)> navs)
    {
        foreach (MetaRule rule in profile.Rules)
            ResolveEmbeddedNavs(rule.Action, navs);
    }

    private static void ResolveEmbeddedNavs(
        MetaAction action,
        IReadOnlyDictionary<string, (string NavType, List<RouteWaypoint> Nodes, uint FollowTargetId, string FollowTargetName)> navs)
    {
        if (action.Kind == MetaActionKind.LoadEmbeddedNavigationRoute)
        {
            string tag = action.SecondaryText;
            string displayName = action.Text;
            action.SecondaryText = displayName;
            action.Text = string.Empty;
            action.EmbeddedRoute = navs.TryGetValue(tag, out var nav)
                ? BuildNavSettings(nav.NavType, nav.Nodes, nav.FollowTargetId, nav.FollowTargetName)
                : new NavigationSettings();
        }
        foreach (MetaAction child in action.Children)
            ResolveEmbeddedNavs(child, navs);
    }

    private static NavigationSettings BuildNavSettings(
        string navType,
        List<RouteWaypoint> nodes,
        uint followTargetId,
        string followTargetName)
    {
        var settings = new NavigationSettings();
        ApplyNavBody(settings, navType, nodes, followTargetId, followTargetName);
        return settings;
    }

    // ==================================================================
    // NAV: blocks (both inside a full .af meta and in a nav-only file).
    // ==================================================================

    public static bool TryLoadNav(
        string text,
        NavigationSettings target,
        ISpellCatalog spells,
        out string error)
    {
        ArgumentNullException.ThrowIfNull(target);
        ArgumentNullException.ThrowIfNull(spells);
        try
        {
            var cursor = new Cursor(SplitLines(text));
            var navs = new Dictionary<string, (string NavType, List<RouteWaypoint> Nodes,
                uint FollowTargetId, string FollowTargetName)>(StringComparer.Ordinal);
            cursor.SkipBlank();
            while (cursor.L < cursor.Lines.Length)
            {
                Match lead = LeadIn.Match(cursor.Lines[cursor.L]);
                if (!lead.Success)
                    throw cursor.Error("expected 'NAV:' (or a STATE: rule section, refused for a route load).");
                if (lead.Groups["type"].Value == "NAV:")
                {
                    ReadNavBlock(cursor, navs, spells);
                    continue;
                }
                throw cursor.Error(
                    "found a STATE: rule section — this is a Meta profile "
                    + "(possibly with an embedded nav), not a stand-alone "
                    + "route; load it from the metas/ folder instead.");
            }
            if (navs.Count == 0)
                throw cursor.Error(
                    "no NAV: block found — this looks like a Meta profile that belongs "
                    + "in the metas/ folder, not a route.");
            var (navType, nodes, followId, followName) = navs.First().Value;
            ApplyNavBody(target, navType, nodes, followId, followName);
            error = string.Empty;
            return true;
        }
        catch (Exception exception) when (exception is FormatException or RegexMatchTimeoutException)
        {
            error = exception.Message;
            return false;
        }
    }

    public static string SaveNav(NavigationSettings source)
    {
        ArgumentNullException.ThrowIfNull(source);
        var lines = new List<string> { NavOutputHeader };
        WriteNavBlock(lines, "nav0", source);
        return string.Join("\r\n", lines) + "\r\n";
    }

    private static void ReadNavBlock(
        Cursor cursor,
        Dictionary<string, (string NavType, List<RouteWaypoint> Nodes, uint FollowTargetId, string FollowTargetName)> navs,
        ISpellCatalog spells)
    {
        Match header = LeadIn.Match(cursor.Lines[cursor.L]);
        string headerRemainder = TrailingComment.Replace(
            cursor.Lines[cursor.L][(header.Groups["tabs"].Length + "NAV:".Length)..],
            string.Empty);
        Match nav = NavHeader.Match(headerRemainder);
        if (!nav.Success)
        {
            throw cursor.Error(
                "'NAV:' must be followed by a tag literal and a nav type (circular/linear/once/follow).");
        }
        string tag = nav.Groups["l"].Value;
        string navType = nav.Groups["l2"].Value;
        cursor.L++;
        cursor.SkipBlank();

        var nodes = new List<RouteWaypoint>();
        uint followTargetId = 0u;
        string followTargetName = string.Empty;
        while (true)
        {
            cursor.SkipBlank();
            if (cursor.L >= cursor.Lines.Length)
                break;
            Match lead = LeadIn.Match(cursor.Lines[cursor.L]);
            if (lead.Success)
                break;
            Match nodeOp = AnyNavNodeType.Match(cursor.Lines[cursor.L]);
            if (!nodeOp.Success)
                throw cursor.Error("expected a nav node line (one tab, then a node keyword).");
            string keyword = nodeOp.Groups["type"].Value;
            cursor.C = nodeOp.Length;
            string remainder = cursor.RemainderOfCurrentLine();
            cursor.L++;
            Match args = NavArgs[keyword].Match(remainder);
            if (!args.Success)
                throw cursor.Error($"'{keyword}' arguments do not match the expected shape.");

            if (keyword == "flw")
            {
                followTargetId = ParseHexAsUInt(args.Groups["h"].Value);
                followTargetName = StripDelimiters(args.Groups["s"].Value);
                continue;
            }
            nodes.Add(ReadNavNode(keyword, args, spells));
        }
        navs[tag] = (navType, nodes, followTargetId, followTargetName);
    }

    private static RouteWaypoint ReadNavNode(string keyword, Match args, ISpellCatalog spells)
    {
        double x = args.Groups["d"].Success ? ParseDouble(args.Groups["d"].Value) : 0d;
        double y = args.Groups["d2"].Success ? ParseDouble(args.Groups["d2"].Value) : 0d;
        double z = args.Groups["d3"].Success ? ParseDouble(args.Groups["d3"].Value) : 0d;
        var waypoint = new RouteWaypoint
        {
            Type = NodeWaypointType(keyword),
            Position = new PluginNavigationPosition(0u, x, y, z, 0f, IsOutdoor: true),
        };
        switch (keyword)
        {
            case "prt":
                waypoint.ObjectId = ParseHexAsUInt(args.Groups["h"].Value);
                break;
            case "rcl":
                waypoint.RecallSpellName = StripDelimiters(args.Groups["s"].Value);
                waypoint.RecallSpellId = ResolveSpellIdByName(spells, waypoint.RecallSpellName);
                break;
            case "pau":
                waypoint.DurationMilliseconds = checked((int)Math.Round(
                    ParseDouble(args.Groups["d4"].Value),
                    MidpointRounding.AwayFromZero));
                break;
            case "cht":
                waypoint.Text = StripDelimiters(args.Groups["s"].Value);
                break;
            case "vnd":
                waypoint.ObjectId = ParseHexAsUInt(args.Groups["h"].Value);
                waypoint.ObjectName = StripDelimiters(args.Groups["s"].Value);
                break;
            case "ptl" or "tlk":
                waypoint.ObjectName = StripDelimiters(args.Groups["s"].Value);
                waypoint.LegacyObjectClass = ParseInt(args.Groups["i"].Value);
                waypoint.LegacyReferenceValid = true;
                waypoint.ReferencePosition = new PluginNavigationPosition(
                    0u,
                    ParseDouble(args.Groups["d4"].Value),
                    ParseDouble(args.Groups["d5"].Value),
                    ParseDouble(args.Groups["d6"].Value),
                    0f,
                    IsOutdoor: true);
                break;
            case "jmp":
                waypoint.JumpHeadingDegrees = checked((float)ParseDouble(args.Groups["d4"].Value));
                waypoint.JumpRun = StripDelimiters(args.Groups["s"].Value) == "True";
                waypoint.JumpChargeMilliseconds = checked((int)Math.Round(
                    ParseDouble(args.Groups["d5"].Value),
                    MidpointRounding.AwayFromZero));
                break;
        }
        return waypoint;
    }

    private static void ApplyNavBody(
        NavigationSettings target,
        string navType,
        List<RouteWaypoint> nodes,
        uint followTargetId,
        string followTargetName)
    {
        target.Mode = navType switch
        {
            "circular" => RouteMode.Circular,
            "linear" => RouteMode.Linear,
            "follow" => RouteMode.Target,
            "once" => RouteMode.Once,
            _ => throw new FormatException($"unknown nav type '{navType}'."),
        };
        target.Waypoints.Clear();
        if (target.Mode == RouteMode.Target)
        {
            target.FollowTargetObjectId = followTargetId;
            target.FollowTargetName = followTargetName;
            return;
        }
        target.Waypoints.AddRange(nodes);
    }

    // ------------------------------------------------------------------
    // Writing.
    // ------------------------------------------------------------------

    private static void WriteCondition(
        List<string> lines,
        MetaCondition value,
        string label,
        int labelTabs,
        int depth)
    {
        string tabs = new('\t', labelTabs);
        lines.Add($"{tabs}{label}\t{RenderConditionHead(value)}");
        if (value.Kind is MetaConditionKind.All or MetaConditionKind.Any)
        {
            foreach (MetaCondition child in value.Children)
                WriteConditionNested(lines, child, depth + 1);
        }
    }

    private static void WriteConditionNested(List<string> lines, MetaCondition value, int depth)
    {
        lines.Add(new string('\t', depth) + RenderConditionHead(value));
        if (value.Kind is MetaConditionKind.All or MetaConditionKind.Any)
        {
            foreach (MetaCondition child in value.Children)
                WriteConditionNested(lines, child, depth + 1);
        }
    }

    private static string RenderConditionHead(MetaCondition value)
    {
        string keyword = ConditionKeyword(value.Kind);
        if (keyword == "Not")
        {
            return "Not " + RenderConditionHead(
                value.Children.FirstOrDefault() ?? MetaCondition.Always());
        }
        return keyword switch
        {
            "ChatMatch" or "Expr" => $"{keyword} {{{value.Text}}}",
            "MainSlotsLE" or "SecsInStateGE" or "PSecsInStateGE" or "BuPercentGE" =>
                $"{keyword} {FormatNumber(value.Number)}",
            "ItemCountLE" or "ItemCountGE" =>
                $"{keyword} {FormatNumber(value.Number)} {{{value.Text}}}",
            "MobsInDist_Name" =>
                $"{keyword} {FormatNumber(value.Number)} {FormatNumber(value.SecondaryNumber)} {{{value.Text}}}",
            "MobsInDist_Priority" =>
                $"{keyword} {FormatNumber(value.Number)} {FormatNumber(value.SecondaryNumber)} {FormatNumber(value.TertiaryNumber)}",
            "NoMobsInDist" or "DistToRteGE" => $"{keyword} {FormatNumber(value.Number)}",
            "BlockE" or "CellE" => $"{keyword} {FormatHex(value.Number)}",
            "SecsOnSpellGE" => $"{keyword} {FormatNumber(value.SecondaryNumber)} {FormatNumber(value.Number)}",
            "ChatCapture" => $"{keyword} {{{value.Text}}} {{{value.SecondaryText}}}",
            _ => keyword,
        };
    }

    private static void WriteAction(
        List<string> lines,
        MetaAction value,
        string label,
        int labelTabs,
        int depth,
        IReadOnlyDictionary<MetaAction, string> embedTags)
    {
        string tabs = new('\t', labelTabs);
        string keyword = ActionKeyword(value.Kind);
        lines.Add($"{tabs}{label}\t{RenderActionSameLine(keyword, value, embedTags)}");
        if (keyword == "DoAll")
        {
            foreach (MetaAction child in value.Children)
                WriteActionNested(lines, child, depth + 1, embedTags);
        }
    }

    private static void WriteActionNested(
        List<string> lines,
        MetaAction value,
        int depth,
        IReadOnlyDictionary<MetaAction, string> embedTags)
    {
        string keyword = ActionKeyword(value.Kind);
        lines.Add(new string('\t', depth) + RenderActionSameLine(keyword, value, embedTags));
        if (keyword == "DoAll")
        {
            foreach (MetaAction child in value.Children)
                WriteActionNested(lines, child, depth + 1, embedTags);
        }
    }

    private static string RenderActionSameLine(
        string keyword,
        MetaAction value,
        IReadOnlyDictionary<MetaAction, string> embedTags) => keyword switch
    {
        "SetState" or "Chat" or "DoExpr" or "ChatExpr" => $"{keyword} {{{value.Text}}}",
        "CallState" => $"{keyword} {{{value.Text}}} {{{value.SecondaryText}}}",
        "SetWatchdog" =>
            $"{keyword} {FormatNumber(value.Number)} {FormatNumber(value.SecondaryNumber)} {{{value.Text}}}",
        "GetOpt" or "SetOpt" or "CreateView" => $"{keyword} {{{value.Text}}} {{{value.SecondaryText}}}",
        "DestroyView" => $"{keyword}  {{{value.Text}}}",
        "EmbedNav" => $"{keyword} {(embedTags.TryGetValue(value, out string? tag) ? tag : "unresolved")} {{{value.SecondaryText}}}",
        _ => keyword,
    };

    private static void WriteNavBlock(List<string> lines, string tag, NavigationSettings source)
    {
        string navType = source.Mode switch
        {
            RouteMode.Circular => "circular",
            RouteMode.Linear => "linear",
            RouteMode.Target => "follow",
            RouteMode.Once => "once",
            _ => throw new InvalidOperationException("unknown navigation mode."),
        };
        lines.Add($"NAV: {tag} {navType} ~~ {{");
        if (source.Mode == RouteMode.Target)
        {
            lines.Add(
                $"\tflw {FormatHex(source.FollowTargetObjectId)} {{{source.FollowTargetName}}}");
            lines.Add("~~ }");
            return;
        }
        foreach (RouteWaypoint waypoint in source.Waypoints)
            lines.Add(RenderNavNode(waypoint));
        lines.Add("~~ }");
    }

    private static string RenderNavNode(RouteWaypoint waypoint)
    {
        double x = waypoint.Position.EastWest;
        double y = waypoint.Position.NorthSouth;
        double z = waypoint.Position.Elevation;
        return waypoint.Type switch
        {
            RouteWaypointType.Point or RouteWaypointType.Checkpoint =>
                $"\t{NodeKeyword(waypoint.Type)} {FormatNumber(x)} {FormatNumber(y)} {FormatNumber(z)}",
            RouteWaypointType.Portal =>
                $"\tprt {FormatNumber(x)} {FormatNumber(y)} {FormatNumber(z)} {FormatHex(waypoint.ObjectId)}",
            RouteWaypointType.Recall =>
                $"\trcl {FormatNumber(x)} {FormatNumber(y)} {FormatNumber(z)} {{{waypoint.RecallSpellName}}}",
            RouteWaypointType.Pause =>
                $"\tpau {FormatNumber(x)} {FormatNumber(y)} {FormatNumber(z)} {FormatNumber(waypoint.DurationMilliseconds)}",
            RouteWaypointType.ChatCommand =>
                $"\tcht {FormatNumber(x)} {FormatNumber(y)} {FormatNumber(z)} {{{waypoint.Text}}}",
            RouteWaypointType.OpenVendor =>
                $"\tvnd {FormatNumber(x)} {FormatNumber(y)} {FormatNumber(z)} {FormatHex(waypoint.ObjectId)} {{{waypoint.ObjectName}}}",
            RouteWaypointType.PortalByName or RouteWaypointType.UseNpc =>
                $"\t{NodeKeyword(waypoint.Type)} {FormatNumber(x)} {FormatNumber(y)} {FormatNumber(z)} "
                + $"{FormatNumber(waypoint.ReferencePosition.EastWest)} {FormatNumber(waypoint.ReferencePosition.NorthSouth)} {FormatNumber(waypoint.ReferencePosition.Elevation)} "
                + $"{waypoint.LegacyObjectClass} {{{waypoint.ObjectName}}}",
            RouteWaypointType.Jump =>
                $"\tjmp {FormatNumber(x)} {FormatNumber(y)} {FormatNumber(z)} {FormatNumber(waypoint.JumpHeadingDegrees)} "
                + $"{{{(waypoint.JumpRun ? "True" : "False")}}} {FormatNumber(waypoint.JumpChargeMilliseconds)}",
            _ => throw new InvalidOperationException($"unknown waypoint type {waypoint.Type}."),
        };
    }

    // ------------------------------------------------------------------
    // Small helpers.
    // ------------------------------------------------------------------

    private static string[] SplitLines(string text) => (text ?? string.Empty)
        .Replace("\r\n", "\n", StringComparison.Ordinal)
        .Split('\n');

    private static string StripDelimiters(string value) =>
        value.Length >= 2 ? value[1..^1] : string.Empty;

    private static int ParseInt(string text) => int.Parse(
        text, NumberStyles.Integer, CultureInfo.InvariantCulture);

    private static double ParseDouble(string text) => double.Parse(
        text, NumberStyles.Float, CultureInfo.InvariantCulture);

    private static int ParseHexAsInt(string text)
    {
        uint unsigned = uint.Parse(text, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
        return unchecked((int)unsigned);
    }

    private static uint ParseHexAsUInt(string text) =>
        uint.Parse(text, NumberStyles.HexNumber, CultureInfo.InvariantCulture);

    private static string FormatNumber(double value) => value.ToString(CultureInfo.InvariantCulture);

    private static string FormatHex(double value) => unchecked((uint)checked((int)value))
        .ToString("X8", CultureInfo.InvariantCulture);

    private static string FormatHex(uint value) => value.ToString("X8", CultureInfo.InvariantCulture);

    private static uint ResolveSpellIdByName(ISpellCatalog spells, string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return 0u;
        foreach (PluginSpellInfo spell in spells.KnownSelfBuffs)
        {
            if (spell.Name.Equals(name, StringComparison.OrdinalIgnoreCase))
                return spell.SpellId;
        }
        foreach (PluginSpellInfo spell in spells.KnownCombatSpells)
        {
            if (spell.Name.Equals(name, StringComparison.OrdinalIgnoreCase))
                return spell.SpellId;
        }
        return 0u;
    }

    private static RouteWaypointType NodeWaypointType(string keyword) => keyword switch
    {
        "pnt" => RouteWaypointType.Point,
        "prt" => RouteWaypointType.Portal,
        "rcl" => RouteWaypointType.Recall,
        "pau" => RouteWaypointType.Pause,
        "cht" => RouteWaypointType.ChatCommand,
        "vnd" => RouteWaypointType.OpenVendor,
        "ptl" => RouteWaypointType.PortalByName,
        "tlk" => RouteWaypointType.UseNpc,
        "chk" => RouteWaypointType.Checkpoint,
        "jmp" => RouteWaypointType.Jump,
        _ => throw new FormatException($"unknown nav node keyword '{keyword}'."),
    };

    private static string NodeKeyword(RouteWaypointType type) => type switch
    {
        RouteWaypointType.Point => "pnt",
        RouteWaypointType.Portal => "prt",
        RouteWaypointType.Recall => "rcl",
        RouteWaypointType.Pause => "pau",
        RouteWaypointType.ChatCommand => "cht",
        RouteWaypointType.OpenVendor => "vnd",
        RouteWaypointType.PortalByName => "ptl",
        RouteWaypointType.UseNpc => "tlk",
        RouteWaypointType.Checkpoint => "chk",
        RouteWaypointType.Jump => "jmp",
        _ => throw new InvalidOperationException($"unknown waypoint type {type}."),
    };

    private static MetaConditionKind ConditionKind(string keyword) => keyword switch
    {
        "Never" => MetaConditionKind.Never,
        "Always" => MetaConditionKind.Always,
        "All" => MetaConditionKind.All,
        "Any" => MetaConditionKind.Any,
        "ChatMatch" => MetaConditionKind.ChatMessage,
        "MainSlotsLE" => MetaConditionKind.PackSlotsLessThanOrEqual,
        "SecsInStateGE" => MetaConditionKind.SecondsInStateGreaterThanOrEqual,
        "NavEmpty" => MetaConditionKind.NavigationRouteEmpty,
        "Death" => MetaConditionKind.CharacterDeath,
        "VendorOpen" => MetaConditionKind.AnyVendorOpen,
        "VendorClosed" => MetaConditionKind.VendorClosed,
        "ItemCountLE" => MetaConditionKind.InventoryItemCountLessThanOrEqual,
        "ItemCountGE" => MetaConditionKind.InventoryItemCountGreaterThanOrEqual,
        "MobsInDist_Name" => MetaConditionKind.MonsterNameCountWithinDistance,
        "MobsInDist_Priority" => MetaConditionKind.MonsterPriorityCountWithinDistance,
        "NeedToBuff" => MetaConditionKind.NeedToBuff,
        "NoMobsInDist" => MetaConditionKind.NoMonstersWithinDistance,
        "BlockE" => MetaConditionKind.LandblockEquals,
        "CellE" => MetaConditionKind.LandcellEquals,
        "IntoPortal" => MetaConditionKind.PortalspaceEntered,
        "ExitPortal" => MetaConditionKind.PortalspaceExited,
        "Not" => MetaConditionKind.Not,
        "PSecsInStateGE" => MetaConditionKind.PersistentSecondsInStateGreaterThanOrEqual,
        "SecsOnSpellGE" => MetaConditionKind.TimeLeftOnSpellGreaterThanOrEqual,
        "BuPercentGE" => MetaConditionKind.BurdenPercentGreaterThanOrEqual,
        "DistToRteGE" => MetaConditionKind.DistanceFromAnyRoutePointGreaterThanOrEqual,
        "Expr" => MetaConditionKind.Expression,
        "ChatCapture" => MetaConditionKind.ChatMessageCapture,
        _ => throw new FormatException($"unknown Condition keyword '{keyword}'."),
    };

    private static string ConditionKeyword(MetaConditionKind kind) => kind switch
    {
        MetaConditionKind.Never => "Never",
        MetaConditionKind.Always => "Always",
        MetaConditionKind.All => "All",
        MetaConditionKind.Any => "Any",
        MetaConditionKind.ChatMessage => "ChatMatch",
        MetaConditionKind.PackSlotsLessThanOrEqual => "MainSlotsLE",
        MetaConditionKind.SecondsInStateGreaterThanOrEqual => "SecsInStateGE",
        MetaConditionKind.NavigationRouteEmpty => "NavEmpty",
        MetaConditionKind.CharacterDeath => "Death",
        MetaConditionKind.AnyVendorOpen => "VendorOpen",
        MetaConditionKind.VendorClosed => "VendorClosed",
        MetaConditionKind.InventoryItemCountLessThanOrEqual => "ItemCountLE",
        MetaConditionKind.InventoryItemCountGreaterThanOrEqual => "ItemCountGE",
        MetaConditionKind.MonsterNameCountWithinDistance => "MobsInDist_Name",
        MetaConditionKind.MonsterPriorityCountWithinDistance => "MobsInDist_Priority",
        MetaConditionKind.NeedToBuff => "NeedToBuff",
        MetaConditionKind.NoMonstersWithinDistance => "NoMobsInDist",
        MetaConditionKind.LandblockEquals => "BlockE",
        MetaConditionKind.LandcellEquals => "CellE",
        MetaConditionKind.PortalspaceEntered => "IntoPortal",
        MetaConditionKind.PortalspaceExited => "ExitPortal",
        MetaConditionKind.Not => "Not",
        MetaConditionKind.PersistentSecondsInStateGreaterThanOrEqual => "PSecsInStateGE",
        MetaConditionKind.TimeLeftOnSpellGreaterThanOrEqual => "SecsOnSpellGE",
        MetaConditionKind.BurdenPercentGreaterThanOrEqual => "BuPercentGE",
        MetaConditionKind.DistanceFromAnyRoutePointGreaterThanOrEqual => "DistToRteGE",
        MetaConditionKind.Expression => "Expr",
        MetaConditionKind.ChatMessageCapture => "ChatCapture",
        _ => throw new InvalidOperationException($"unsupported Meta condition {kind}."),
    };

    private static MetaActionKind ActionKind(string keyword) => keyword switch
    {
        "None" => MetaActionKind.None,
        "SetState" => MetaActionKind.SetMetaState,
        "Chat" => MetaActionKind.ChatCommand,
        "DoAll" => MetaActionKind.All,
        "EmbedNav" => MetaActionKind.LoadEmbeddedNavigationRoute,
        "CallState" => MetaActionKind.CallMetaState,
        "Return" => MetaActionKind.ReturnFromCall,
        "DoExpr" => MetaActionKind.ExpressionAction,
        "ChatExpr" => MetaActionKind.ChatExpression,
        "SetWatchdog" => MetaActionKind.SetWatchdog,
        "ClearWatchdog" => MetaActionKind.ClearWatchdog,
        "GetOpt" => MetaActionKind.GetVtankOption,
        "SetOpt" => MetaActionKind.SetVtankOption,
        "CreateView" => MetaActionKind.CreateView,
        "DestroyView" => MetaActionKind.DestroyView,
        "DestroyAllViews" => MetaActionKind.DestroyAllViews,
        _ => throw new FormatException($"unknown Action keyword '{keyword}'."),
    };

    private static string ActionKeyword(MetaActionKind kind) => kind switch
    {
        MetaActionKind.None => "None",
        MetaActionKind.SetMetaState => "SetState",
        MetaActionKind.ChatCommand => "Chat",
        MetaActionKind.All => "DoAll",
        MetaActionKind.LoadEmbeddedNavigationRoute => "EmbedNav",
        MetaActionKind.CallMetaState => "CallState",
        MetaActionKind.ReturnFromCall => "Return",
        MetaActionKind.ExpressionAction => "DoExpr",
        MetaActionKind.ChatExpression => "ChatExpr",
        MetaActionKind.SetWatchdog => "SetWatchdog",
        MetaActionKind.ClearWatchdog => "ClearWatchdog",
        MetaActionKind.GetVtankOption => "GetOpt",
        MetaActionKind.SetVtankOption => "SetOpt",
        MetaActionKind.CreateView => "CreateView",
        MetaActionKind.DestroyView => "DestroyView",
        MetaActionKind.DestroyAllViews => "DestroyAllViews",
        _ => throw new InvalidOperationException($"unsupported Meta action {kind}."),
    };
}
