namespace AcDream.Plugins.MossTank;

internal enum VtankSettingValueType
{
    Bool = 1,
    Double = 2,
    Int = 3,
    Single = 4,
    String = 5,
    Enum = 6,
    Custom = 7,
}

internal static class VtankOptionCatalog
{
    internal static readonly string[] Names =
    [
        "EnableLooting", "EnableNav", "EnableBuffing", "EnableCombat",
        "SpellDiffExcessThreshold-Hunt", "SpellDiffExcessThreshold-Buff",
        "ArrowheadFletchDiffExcessThreshold", "Recharge-Norm-HitP",
        "Recharge-Norm-Stam", "Recharge-Norm-Mana", "Recharge-NoTarg-HitP",
        "Recharge-NoTarg-Stam", "Recharge-NoTarg-Mana", "Recharge-Helper-HitP",
        "Recharge-Helper-Stam", "Recharge-Helper-Mana", "DoHelp",
        "AttackDistance", "AttackMinimumDistance", "ApproachDistance",
        "RingDistance", "CorpseApproachRange-Max", "CorpseApproachRange-Min",
        "NavCloseStopRange", "NavFarStopRange", "UsePortalDistance",
        "HelperDistanceHitP", "HelperDistanceStam", "HelperDistanceMana",
        "MinimumRingTargets", "DefaultMeleeAttackHeight", "CastDispelSelf",
        "UseDispelItems", "AutoCram", "AutoStack", "ReadUnknownScrolls",
        "UseDispelDrum", "SwitchWandsToDebuff", "AutoCraftItems",
        "UseHealersHeart", "JumpOutWandCasting", "LootAllCorpses",
        "LootFellowCorpses", "DoJiggle", "RandomHelperBuffs",
        "RandomHelperIntervalSeconds", "IdlePeaceMode", "TargetLock",
        "StopMacroOnDeath", "UseArcs", "ArcRange", "TargetSelectMethod",
        "TargetSelectAngleRange", "IdleBuffTopoff", "IdleBuffTopoffTimeSeconds",
        "RebuffTimeRemainingSeconds", "RefillWornMana",
        "RefillWornMana-Item-ManaPercent", "BuffProfile-Prots",
        "BuffProfile-Banes", "BuffProfile_Prots", "BuffProfile_Banes",
        "DebuffEachFirst", "AutoAttackPower", "LootPriorityBoost",
        "CorpseCacheTimeoutMinutes", "CorpseItemAppearanceTimeoutSeconds",
        "CorpseItemIDTimeoutSeconds", "DebuffSelectionMethod",
        "ManaStoneLootCount", "ManaTankMinimumMana", "SplitPeas",
        "SpellCompMin-Critical", "SpellCompMin-Normal", "SpellCompMin-Idle",
        "RechargeBoostTimeSeconds", "RechargeBoostAmount", "UseSpecialAmmo",
        "OpenDoors", "DoorIDRange", "DoorOpenRange",
        "DoorLockpickDiffExcessThreshold", "ManaChargesWhenOff",
        "AutoFellowManagement", "MinimumHealKitSuccessChance",
        "UseKitsInMagicMode", "StaminaToHealthMultiplier",
        "ManaToHealthMultiplier", "NavPriorityBoost", "DeleteGhostMonsters",
        "GhostMonsterSpellAttemptCount", "WhoYouGonnaCall",
        "BlacklistMonsterAttemptCount", "BlacklistMonsterTimeoutSeconds",
        "CombineSalvage", "LootOnlyRareCorpses",
        "DeleteGhostMonstersByHPTracker", "GhostDeleteHPTrackerSeconds",
        "GoToPeaceModeToUseKits", "UseRecklessness", "DebuffPrecastSeconds",
        "ClearLevelBoostFlagOnCast", "IdleCraftCount_HealthKits",
        "IdleCraftCount_StamKits", "IdleCraftCount_ManaKits",
        "IdleCraftCount_HealthFood", "IdleCraftCount_StamFood",
        "IdleCraftCount_ManaFood", "BuffCastRecast_Seconds",
        "BuffCastRecastReset_Seconds", "EnableMeta", "BlacklistedSpellComps",
        "DropToPeaceModeRetryCount", "FollowAroundCorners",
        "BlacklistCorpseOpenAttemptCount", "BlacklistCorpseOpenTimeoutSeconds",
        "SummonPets", "PetRangeMode", "PetCustomRange", "PetRefillCount-Idle",
        "PetRefillCount-Normal", "CorpseOpenTimeoutSeconds",
        "PetMonsterDensity", "CorpseLootItemMaxAttempts", "FastCastBuffs",
        "UseBreakableTurnTo", "UseProjectileAwareness",
        "CollisionProjectileRadius", "CollisionStepDistance",
        "ShowCollisionDebug", "MaximumCollisionChecksPerTick", "SpellRangeFudge",
        "BuffWithUntrained-Item", "BuffWithUntrained-Creature",
        "BuffWithUntrained-Life", "AllowDebuffFallback", "RechargeHandlerSet",
    ];

    private static readonly IReadOnlyDictionary<string, MonsterValue> Defaults =
        new Dictionary<string, MonsterValue>(StringComparer.OrdinalIgnoreCase)
        {
        ["EnableLooting"] = MonsterValue.FromBoolean(false),
        ["EnableNav"] = MonsterValue.FromBoolean(false),
        ["EnableBuffing"] = MonsterValue.FromBoolean(true),
        ["EnableCombat"] = MonsterValue.FromBoolean(true),
        ["SpellDiffExcessThreshold-Hunt"] = MonsterValue.FromNumber(25d),
        ["SpellDiffExcessThreshold-Buff"] = MonsterValue.FromNumber(5d),
        ["ArrowheadFletchDiffExcessThreshold"] = MonsterValue.FromNumber(10d),
        ["Recharge-Norm-HitP"] = MonsterValue.FromNumber(75d),
        ["Recharge-Norm-Stam"] = MonsterValue.FromNumber(50d),
        ["Recharge-Norm-Mana"] = MonsterValue.FromNumber(50d),
        ["Recharge-NoTarg-HitP"] = MonsterValue.FromNumber(1d),
        ["Recharge-NoTarg-Stam"] = MonsterValue.FromNumber(1d),
        ["Recharge-NoTarg-Mana"] = MonsterValue.FromNumber(1d),
        ["Recharge-Helper-HitP"] = MonsterValue.FromNumber(20d),
        ["Recharge-Helper-Stam"] = MonsterValue.FromNumber(1d),
        ["Recharge-Helper-Mana"] = MonsterValue.FromNumber(1d),
        ["DoHelp"] = MonsterValue.FromBoolean(true),
        ["AttackDistance"] = MonsterValue.FromNumber(0.0208333333333333d),
        ["AttackMinimumDistance"] = MonsterValue.FromNumber(0d),
        ["ApproachDistance"] = MonsterValue.FromNumber(0d),
        ["RingDistance"] = MonsterValue.FromNumber(0.0208333333333333d),
        ["CorpseApproachRange-Max"] = MonsterValue.FromNumber(0d),
        ["CorpseApproachRange-Min"] = MonsterValue.FromNumber(0.014d),
        ["NavCloseStopRange"] = MonsterValue.FromNumber(0.00833333333333333d),
        ["NavFarStopRange"] = MonsterValue.FromNumber(999999d),
        ["UsePortalDistance"] = MonsterValue.FromNumber(0.0166666666666667d),
        ["HelperDistanceHitP"] = MonsterValue.FromNumber(0.310416666666667d),
        ["HelperDistanceStam"] = MonsterValue.FromNumber(0.310416666666667d),
        ["HelperDistanceMana"] = MonsterValue.FromNumber(0.166666666666667d),
        ["MinimumRingTargets"] = MonsterValue.FromNumber(4d),
        ["DefaultMeleeAttackHeight"] = MonsterValue.FromNumber(2d),
        ["CastDispelSelf"] = MonsterValue.FromBoolean(false),
        ["UseDispelItems"] = MonsterValue.FromBoolean(false),
        ["AutoCram"] = MonsterValue.FromBoolean(false),
        ["AutoStack"] = MonsterValue.FromBoolean(true),
        ["ReadUnknownScrolls"] = MonsterValue.FromBoolean(true),
        ["UseDispelDrum"] = MonsterValue.FromBoolean(false),
        ["SwitchWandsToDebuff"] = MonsterValue.FromBoolean(false),
        ["AutoCraftItems"] = MonsterValue.FromBoolean(true),
        ["UseHealersHeart"] = MonsterValue.FromBoolean(true),
        ["JumpOutWandCasting"] = MonsterValue.FromBoolean(false),
        ["LootAllCorpses"] = MonsterValue.FromBoolean(false),
        ["LootFellowCorpses"] = MonsterValue.FromBoolean(false),
        ["DoJiggle"] = MonsterValue.FromBoolean(false),
        ["RandomHelperBuffs"] = MonsterValue.FromBoolean(false),
        ["RandomHelperIntervalSeconds"] = MonsterValue.FromNumber(5d),
        ["IdlePeaceMode"] = MonsterValue.FromBoolean(false),
        ["TargetLock"] = MonsterValue.FromBoolean(false),
        ["StopMacroOnDeath"] = MonsterValue.FromBoolean(true),
        ["UseArcs"] = MonsterValue.FromNumber(1d),
        ["ArcRange"] = MonsterValue.FromNumber(0.0208333333333333d),
        ["TargetSelectMethod"] = MonsterValue.FromNumber(3d),
        ["TargetSelectAngleRange"] = MonsterValue.FromNumber(0.0208333333333333d),
        ["IdleBuffTopoff"] = MonsterValue.FromBoolean(false),
        ["IdleBuffTopoffTimeSeconds"] = MonsterValue.FromNumber(1200d),
        ["RebuffTimeRemainingSeconds"] = MonsterValue.FromNumber(300d),
        ["RefillWornMana"] = MonsterValue.FromBoolean(true),
        ["RefillWornMana-Item-ManaPercent"] = MonsterValue.FromNumber(33d),
        ["BuffProfile-Prots"] = MonsterValue.FromText("ALFCBPS"),
        ["BuffProfile-Banes"] = MonsterValue.FromText("ALFCBPS"),
        ["BuffProfile_Prots"] = MonsterValue.FromNumber(2d),
        ["BuffProfile_Banes"] = MonsterValue.FromNumber(2d),
        ["DebuffEachFirst"] = MonsterValue.FromNumber(1d),
        ["AutoAttackPower"] = MonsterValue.FromBoolean(true),
        ["LootPriorityBoost"] = MonsterValue.FromBoolean(false),
        ["CorpseCacheTimeoutMinutes"] = MonsterValue.FromNumber(60d),
        ["CorpseItemAppearanceTimeoutSeconds"] = MonsterValue.FromNumber(6d),
        ["CorpseItemIDTimeoutSeconds"] = MonsterValue.FromNumber(60d),
        ["DebuffSelectionMethod"] = MonsterValue.FromNumber(2d),
        ["ManaStoneLootCount"] = MonsterValue.FromNumber(4d),
        ["ManaTankMinimumMana"] = MonsterValue.FromNumber(1000d),
        ["SplitPeas"] = MonsterValue.FromBoolean(true),
        ["SpellCompMin-Critical"] = MonsterValue.FromNumber(4d),
        ["SpellCompMin-Normal"] = MonsterValue.FromNumber(20d),
        ["SpellCompMin-Idle"] = MonsterValue.FromNumber(20d),
        ["RechargeBoostTimeSeconds"] = MonsterValue.FromNumber(5d),
        ["RechargeBoostAmount"] = MonsterValue.FromNumber(40d),
        ["UseSpecialAmmo"] = MonsterValue.FromNumber(0d),
        ["OpenDoors"] = MonsterValue.FromBoolean(false),
        ["DoorIDRange"] = MonsterValue.FromNumber(0.0833333333333333d),
        ["DoorOpenRange"] = MonsterValue.FromNumber(0.0166666666666667d),
        ["DoorLockpickDiffExcessThreshold"] = MonsterValue.FromNumber(-50d),
        ["ManaChargesWhenOff"] = MonsterValue.FromBoolean(true),
        ["AutoFellowManagement"] = MonsterValue.FromBoolean(true),
        ["MinimumHealKitSuccessChance"] = MonsterValue.FromNumber(95d),
        ["UseKitsInMagicMode"] = MonsterValue.FromBoolean(true),
        ["StaminaToHealthMultiplier"] = MonsterValue.FromNumber(1.9d),
        ["ManaToHealthMultiplier"] = MonsterValue.FromNumber(2.8d),
        ["NavPriorityBoost"] = MonsterValue.FromBoolean(false),
        ["DeleteGhostMonsters"] = MonsterValue.FromBoolean(true),
        ["GhostMonsterSpellAttemptCount"] = MonsterValue.FromNumber(200d),
        ["WhoYouGonnaCall"] = MonsterValue.FromBoolean(true),
        ["BlacklistMonsterAttemptCount"] = MonsterValue.FromNumber(4d),
        ["BlacklistMonsterTimeoutSeconds"] = MonsterValue.FromNumber(120d),
        ["CombineSalvage"] = MonsterValue.FromBoolean(true),
        ["LootOnlyRareCorpses"] = MonsterValue.FromBoolean(false),
        ["DeleteGhostMonstersByHPTracker"] = MonsterValue.FromBoolean(true),
        ["GhostDeleteHPTrackerSeconds"] = MonsterValue.FromNumber(30d),
        ["GoToPeaceModeToUseKits"] = MonsterValue.FromBoolean(false),
        ["UseRecklessness"] = MonsterValue.FromBoolean(true),
        ["DebuffPrecastSeconds"] = MonsterValue.FromNumber(5d),
        ["ClearLevelBoostFlagOnCast"] = MonsterValue.FromBoolean(true),
        ["IdleCraftCount_HealthKits"] = MonsterValue.FromNumber(2d),
        ["IdleCraftCount_StamKits"] = MonsterValue.FromNumber(2d),
        ["IdleCraftCount_ManaKits"] = MonsterValue.FromNumber(2d),
        ["IdleCraftCount_HealthFood"] = MonsterValue.FromNumber(15d),
        ["IdleCraftCount_StamFood"] = MonsterValue.FromNumber(15d),
        ["IdleCraftCount_ManaFood"] = MonsterValue.FromNumber(15d),
        ["BuffCastRecast_Seconds"] = MonsterValue.FromNumber(30d),
        ["BuffCastRecastReset_Seconds"] = MonsterValue.FromNumber(30d),
        ["EnableMeta"] = MonsterValue.FromBoolean(false),
        ["BlacklistedSpellComps"] = MonsterValue.FromText(string.Empty),
        ["DropToPeaceModeRetryCount"] = MonsterValue.FromNumber(34d),
        ["FollowAroundCorners"] = MonsterValue.FromBoolean(true),
        ["BlacklistCorpseOpenAttemptCount"] = MonsterValue.FromNumber(30d),
        ["BlacklistCorpseOpenTimeoutSeconds"] = MonsterValue.FromNumber(200d),
        ["SummonPets"] = MonsterValue.FromBoolean(true),
        ["PetRangeMode"] = MonsterValue.FromNumber(0d),
        ["PetCustomRange"] = MonsterValue.FromNumber(0.0208333333333333d),
        ["PetRefillCount-Idle"] = MonsterValue.FromNumber(3d),
        ["PetRefillCount-Normal"] = MonsterValue.FromNumber(1d),
        ["CorpseOpenTimeoutSeconds"] = MonsterValue.FromNumber(1.5d),
        ["PetMonsterDensity"] = MonsterValue.FromNumber(1d),
        ["CorpseLootItemMaxAttempts"] = MonsterValue.FromNumber(20d),
        ["FastCastBuffs"] = MonsterValue.FromBoolean(false),
        ["UseBreakableTurnTo"] = MonsterValue.FromBoolean(true),
        ["UseProjectileAwareness"] = MonsterValue.FromBoolean(true),
        ["CollisionProjectileRadius"] = MonsterValue.FromNumber(0.4d),
        ["CollisionStepDistance"] = MonsterValue.FromNumber(0.7d),
        ["ShowCollisionDebug"] = MonsterValue.FromBoolean(false),
        ["MaximumCollisionChecksPerTick"] = MonsterValue.FromNumber(500d),
        ["SpellRangeFudge"] = MonsterValue.FromNumber(1d),
        ["BuffWithUntrained-Item"] = MonsterValue.FromNumber(80d),
        ["BuffWithUntrained-Creature"] = MonsterValue.FromNumber(80d),
        ["BuffWithUntrained-Life"] = MonsterValue.FromNumber(80d),
        ["AllowDebuffFallback"] = MonsterValue.FromBoolean(false),
        ["RechargeHandlerSet"] = MonsterValue.FromText("RechargeHandlerSet"),
        };

    private static readonly IReadOnlyDictionary<string, VtankSettingValueType> DeclaredTypes =
        new Dictionary<string, VtankSettingValueType>(StringComparer.OrdinalIgnoreCase)
        {
        ["EnableLooting"] = VtankSettingValueType.Bool,
        ["EnableNav"] = VtankSettingValueType.Bool,
        ["EnableBuffing"] = VtankSettingValueType.Bool,
        ["EnableCombat"] = VtankSettingValueType.Bool,
        ["SpellDiffExcessThreshold-Hunt"] = VtankSettingValueType.Int,
        ["SpellDiffExcessThreshold-Buff"] = VtankSettingValueType.Int,
        ["ArrowheadFletchDiffExcessThreshold"] = VtankSettingValueType.Int,
        ["Recharge-Norm-HitP"] = VtankSettingValueType.Int,
        ["Recharge-Norm-Stam"] = VtankSettingValueType.Int,
        ["Recharge-Norm-Mana"] = VtankSettingValueType.Int,
        ["Recharge-NoTarg-HitP"] = VtankSettingValueType.Int,
        ["Recharge-NoTarg-Stam"] = VtankSettingValueType.Int,
        ["Recharge-NoTarg-Mana"] = VtankSettingValueType.Int,
        ["Recharge-Helper-HitP"] = VtankSettingValueType.Int,
        ["Recharge-Helper-Stam"] = VtankSettingValueType.Int,
        ["Recharge-Helper-Mana"] = VtankSettingValueType.Int,
        ["DoHelp"] = VtankSettingValueType.Bool,
        ["AttackDistance"] = VtankSettingValueType.Double,
        ["AttackMinimumDistance"] = VtankSettingValueType.Double,
        ["ApproachDistance"] = VtankSettingValueType.Double,
        ["RingDistance"] = VtankSettingValueType.Double,
        ["CorpseApproachRange-Max"] = VtankSettingValueType.Double,
        ["CorpseApproachRange-Min"] = VtankSettingValueType.Double,
        ["NavCloseStopRange"] = VtankSettingValueType.Double,
        ["NavFarStopRange"] = VtankSettingValueType.Double,
        ["UsePortalDistance"] = VtankSettingValueType.Double,
        ["HelperDistanceHitP"] = VtankSettingValueType.Double,
        ["HelperDistanceStam"] = VtankSettingValueType.Double,
        ["HelperDistanceMana"] = VtankSettingValueType.Double,
        ["MinimumRingTargets"] = VtankSettingValueType.Int,
        ["DefaultMeleeAttackHeight"] = VtankSettingValueType.Int,
        ["CastDispelSelf"] = VtankSettingValueType.Bool,
        ["UseDispelItems"] = VtankSettingValueType.Bool,
        ["AutoCram"] = VtankSettingValueType.Bool,
        ["AutoStack"] = VtankSettingValueType.Bool,
        ["ReadUnknownScrolls"] = VtankSettingValueType.Bool,
        ["UseDispelDrum"] = VtankSettingValueType.Bool,
        ["SwitchWandsToDebuff"] = VtankSettingValueType.Bool,
        ["AutoCraftItems"] = VtankSettingValueType.Bool,
        ["UseHealersHeart"] = VtankSettingValueType.Bool,
        ["JumpOutWandCasting"] = VtankSettingValueType.Bool,
        ["LootAllCorpses"] = VtankSettingValueType.Bool,
        ["LootFellowCorpses"] = VtankSettingValueType.Bool,
        ["DoJiggle"] = VtankSettingValueType.Bool,
        ["RandomHelperBuffs"] = VtankSettingValueType.Bool,
        ["RandomHelperIntervalSeconds"] = VtankSettingValueType.Double,
        ["IdlePeaceMode"] = VtankSettingValueType.Bool,
        ["TargetLock"] = VtankSettingValueType.Bool,
        ["StopMacroOnDeath"] = VtankSettingValueType.Bool,
        ["UseArcs"] = VtankSettingValueType.Enum,
        ["ArcRange"] = VtankSettingValueType.Double,
        ["TargetSelectMethod"] = VtankSettingValueType.Enum,
        ["TargetSelectAngleRange"] = VtankSettingValueType.Double,
        ["IdleBuffTopoff"] = VtankSettingValueType.Bool,
        ["IdleBuffTopoffTimeSeconds"] = VtankSettingValueType.Int,
        ["RebuffTimeRemainingSeconds"] = VtankSettingValueType.Int,
        ["RefillWornMana"] = VtankSettingValueType.Bool,
        ["RefillWornMana-Item-ManaPercent"] = VtankSettingValueType.Int,
        ["BuffProfile-Prots"] = VtankSettingValueType.String,
        ["BuffProfile-Banes"] = VtankSettingValueType.String,
        ["BuffProfile_Prots"] = VtankSettingValueType.Enum,
        ["BuffProfile_Banes"] = VtankSettingValueType.Enum,
        ["DebuffEachFirst"] = VtankSettingValueType.Enum,
        ["AutoAttackPower"] = VtankSettingValueType.Bool,
        ["LootPriorityBoost"] = VtankSettingValueType.Bool,
        ["CorpseCacheTimeoutMinutes"] = VtankSettingValueType.Double,
        ["CorpseItemAppearanceTimeoutSeconds"] = VtankSettingValueType.Double,
        ["CorpseItemIDTimeoutSeconds"] = VtankSettingValueType.Double,
        ["DebuffSelectionMethod"] = VtankSettingValueType.Enum,
        ["ManaStoneLootCount"] = VtankSettingValueType.Int,
        ["ManaTankMinimumMana"] = VtankSettingValueType.Int,
        ["SplitPeas"] = VtankSettingValueType.Bool,
        ["SpellCompMin-Critical"] = VtankSettingValueType.Int,
        ["SpellCompMin-Normal"] = VtankSettingValueType.Int,
        ["SpellCompMin-Idle"] = VtankSettingValueType.Int,
        ["RechargeBoostTimeSeconds"] = VtankSettingValueType.Double,
        ["RechargeBoostAmount"] = VtankSettingValueType.Int,
        ["UseSpecialAmmo"] = VtankSettingValueType.Enum,
        ["OpenDoors"] = VtankSettingValueType.Bool,
        ["DoorIDRange"] = VtankSettingValueType.Double,
        ["DoorOpenRange"] = VtankSettingValueType.Double,
        ["DoorLockpickDiffExcessThreshold"] = VtankSettingValueType.Int,
        ["ManaChargesWhenOff"] = VtankSettingValueType.Bool,
        ["AutoFellowManagement"] = VtankSettingValueType.Bool,
        ["MinimumHealKitSuccessChance"] = VtankSettingValueType.Int,
        ["UseKitsInMagicMode"] = VtankSettingValueType.Bool,
        ["StaminaToHealthMultiplier"] = VtankSettingValueType.Double,
        ["ManaToHealthMultiplier"] = VtankSettingValueType.Double,
        ["NavPriorityBoost"] = VtankSettingValueType.Bool,
        ["DeleteGhostMonsters"] = VtankSettingValueType.Bool,
        ["GhostMonsterSpellAttemptCount"] = VtankSettingValueType.Int,
        ["WhoYouGonnaCall"] = VtankSettingValueType.Bool,
        ["BlacklistMonsterAttemptCount"] = VtankSettingValueType.Int,
        ["BlacklistMonsterTimeoutSeconds"] = VtankSettingValueType.Int,
        ["CombineSalvage"] = VtankSettingValueType.Bool,
        ["LootOnlyRareCorpses"] = VtankSettingValueType.Bool,
        ["DeleteGhostMonstersByHPTracker"] = VtankSettingValueType.Bool,
        ["GhostDeleteHPTrackerSeconds"] = VtankSettingValueType.Int,
        ["GoToPeaceModeToUseKits"] = VtankSettingValueType.Bool,
        ["UseRecklessness"] = VtankSettingValueType.Bool,
        ["DebuffPrecastSeconds"] = VtankSettingValueType.Int,
        ["ClearLevelBoostFlagOnCast"] = VtankSettingValueType.Bool,
        ["IdleCraftCount_HealthKits"] = VtankSettingValueType.Int,
        ["IdleCraftCount_StamKits"] = VtankSettingValueType.Int,
        ["IdleCraftCount_ManaKits"] = VtankSettingValueType.Int,
        ["IdleCraftCount_HealthFood"] = VtankSettingValueType.Int,
        ["IdleCraftCount_StamFood"] = VtankSettingValueType.Int,
        ["IdleCraftCount_ManaFood"] = VtankSettingValueType.Int,
        ["BuffCastRecast_Seconds"] = VtankSettingValueType.Int,
        ["BuffCastRecastReset_Seconds"] = VtankSettingValueType.Int,
        ["EnableMeta"] = VtankSettingValueType.Bool,
        ["BlacklistedSpellComps"] = VtankSettingValueType.String,
        ["DropToPeaceModeRetryCount"] = VtankSettingValueType.Int,
        ["FollowAroundCorners"] = VtankSettingValueType.Bool,
        ["BlacklistCorpseOpenAttemptCount"] = VtankSettingValueType.Int,
        ["BlacklistCorpseOpenTimeoutSeconds"] = VtankSettingValueType.Int,
        ["SummonPets"] = VtankSettingValueType.Bool,
        ["PetRangeMode"] = VtankSettingValueType.Enum,
        ["PetCustomRange"] = VtankSettingValueType.Double,
        ["PetRefillCount-Idle"] = VtankSettingValueType.Int,
        ["PetRefillCount-Normal"] = VtankSettingValueType.Int,
        ["CorpseOpenTimeoutSeconds"] = VtankSettingValueType.Double,
        ["PetMonsterDensity"] = VtankSettingValueType.Int,
        ["CorpseLootItemMaxAttempts"] = VtankSettingValueType.Int,
        ["FastCastBuffs"] = VtankSettingValueType.Bool,
        ["UseBreakableTurnTo"] = VtankSettingValueType.Bool,
        ["UseProjectileAwareness"] = VtankSettingValueType.Bool,
        ["CollisionProjectileRadius"] = VtankSettingValueType.Double,
        ["CollisionStepDistance"] = VtankSettingValueType.Double,
        ["ShowCollisionDebug"] = VtankSettingValueType.Bool,
        ["MaximumCollisionChecksPerTick"] = VtankSettingValueType.Int,
        ["SpellRangeFudge"] = VtankSettingValueType.Double,
        ["BuffWithUntrained-Item"] = VtankSettingValueType.Int,
        ["BuffWithUntrained-Creature"] = VtankSettingValueType.Int,
        ["BuffWithUntrained-Life"] = VtankSettingValueType.Int,
        ["AllowDebuffFallback"] = VtankSettingValueType.Bool,
        ["RechargeHandlerSet"] = VtankSettingValueType.Custom,
        };

    internal static bool IsKnown(string name) =>
        Names.Contains(name, StringComparer.OrdinalIgnoreCase);

    internal static string Canonical(string name) =>
        Names.First(value => value.Equals(name, StringComparison.OrdinalIgnoreCase));

    internal static MonsterValue Default(string name) =>
        Defaults.TryGetValue(name, out MonsterValue value)
            ? value
            : MonsterValue.FromNumber(0d);

    /// <summary>The <c>eSettingValueType</c> VTank's own Settings row declares for this name.</summary>
    internal static VtankSettingValueType DeclaredType(string name) =>
        DeclaredTypes.TryGetValue(name, out VtankSettingValueType type)
            ? type
            : VtankSettingValueType.Double;

    internal static readonly int[] CategoryBits = VtankDefaultSettingsDatabase
        .SettingCategoryBitmasks.Values
        .SelectMany(DecomposeBits)
        .Distinct()
        .Order()
        .ToArray();

    internal static readonly IReadOnlyDictionary<int, string> CategoryNamesByBit =
        BuildCategoryNamesByBit();

    private static IReadOnlyDictionary<int, string> BuildCategoryNamesByBit()
    {
        IReadOnlyDictionary<string, int> bitmasks = VtankDefaultSettingsDatabase.SettingCategoryBitmasks;
        (string Setting, string Category)[] anchors =
        [
            ("RandomHelperBuffs", "Misc"),
            ("Recharge-Norm-HitP", "Recharge"),
            ("DefaultMeleeAttackHeight", "MeleeCombat"),
            ("SpellDiffExcessThreshold-Hunt", "SpellCombat"),
            ("AttackDistance", "Ranges"),
            ("EnableNav", "Navigation"),
            ("EnableBuffing", "Buffing"),
            ("ArrowheadFletchDiffExcessThreshold", "Crafting"),
            ("EnableLooting", "Looting"),
        ];
        var map = new Dictionary<int, string>();
        foreach ((string setting, string category) in anchors)
            if (bitmasks.TryGetValue(setting, out int bit))
                map[bit] = category;
        return map;
    }

    private static IEnumerable<int> DecomposeBits(int mask)
    {
        for (int bit = 1; bit != 0 && bit <= mask; bit <<= 1)
            if ((mask & bit) != 0)
                yield return bit;
    }
}
