namespace AcDream.Plugins.MossTank;

/// <summary>
/// The pages of the advanced options a setting is shown on. The bit values
/// are the ones a settings profile stores in its <c>SettingsCategories</c>
/// table, so a profile written here files each setting where one written
/// elsewhere does.
/// </summary>
[Flags]
internal enum VtankOptionPage
{
    None = 0,
    Misc = 0x001,
    Recharge = 0x002,
    MeleeCombat = 0x004,
    SpellCombat = 0x008,
    Ranges = 0x010,
    Navigation = 0x020,
    Buffing = 0x040,
    Crafting = 0x080,
    Looting = 0x100,
}

/// <summary>
/// What MossTank knows about each setting beyond its name, type and default
/// (those are in <see cref="VtankOptionCatalog"/>): the pages it is shown
/// on, the text that explains it, the labels of a choice's values, and the
/// default lists a new settings profile starts with.
/// </summary>
internal static class VtankOptionDetails
{
    private const VtankOptionPage Misc = VtankOptionPage.Misc;
    private const VtankOptionPage Recharge = VtankOptionPage.Recharge;
    private const VtankOptionPage Melee = VtankOptionPage.MeleeCombat;
    private const VtankOptionPage Spell = VtankOptionPage.SpellCombat;
    private const VtankOptionPage Combat = Melee | Spell;
    private const VtankOptionPage Ranges = VtankOptionPage.Ranges;
    private const VtankOptionPage Navigation = VtankOptionPage.Navigation;
    private const VtankOptionPage Buffing = VtankOptionPage.Buffing;
    private const VtankOptionPage Crafting = VtankOptionPage.Crafting;
    private const VtankOptionPage Looting = VtankOptionPage.Looting;

    /// <summary>The pages each setting is shown on. A setting not listed has no page of its own.</summary>
    internal static readonly IReadOnlyDictionary<string, VtankOptionPage> Pages =
        new Dictionary<string, VtankOptionPage>(StringComparer.OrdinalIgnoreCase)
        {
            ["EnableLooting"] = Looting,
            ["EnableNav"] = Navigation,
            ["EnableBuffing"] = Buffing,
            ["EnableCombat"] = Combat,
            ["SpellDiffExcessThreshold-Hunt"] = Spell,
            ["SpellDiffExcessThreshold-Buff"] = Buffing,
            ["ArrowheadFletchDiffExcessThreshold"] = Crafting,
            ["Recharge-Norm-HitP"] = Recharge,
            ["Recharge-Norm-Stam"] = Recharge,
            ["Recharge-Norm-Mana"] = Recharge,
            ["Recharge-NoTarg-HitP"] = Recharge,
            ["Recharge-NoTarg-Stam"] = Recharge,
            ["Recharge-NoTarg-Mana"] = Recharge,
            ["Recharge-Helper-HitP"] = Recharge,
            ["Recharge-Helper-Stam"] = Recharge,
            ["Recharge-Helper-Mana"] = Recharge,
            ["DoHelp"] = Recharge,
            ["AttackDistance"] = Ranges,
            ["AttackMinimumDistance"] = Ranges,
            ["ApproachDistance"] = Ranges | Navigation,
            ["RingDistance"] = Ranges | Spell,
            ["CorpseApproachRange-Max"] = Ranges | Navigation,
            ["CorpseApproachRange-Min"] = Ranges | Navigation,
            ["NavCloseStopRange"] = Ranges | Navigation,
            ["NavFarStopRange"] = Ranges | Navigation,
            ["UsePortalDistance"] = Ranges | Navigation,
            ["HelperDistanceHitP"] = Ranges | Recharge,
            ["HelperDistanceStam"] = Ranges | Recharge,
            ["HelperDistanceMana"] = Ranges | Recharge,
            ["MinimumRingTargets"] = Spell,
            ["DefaultMeleeAttackHeight"] = Melee,
            ["CastDispelSelf"] = Recharge,
            ["UseDispelItems"] = Recharge,
            ["AutoCram"] = Misc,
            ["AutoStack"] = Misc,
            ["ReadUnknownScrolls"] = Looting,
            ["UseDispelDrum"] = Recharge,
            ["SwitchWandsToDebuff"] = Spell,
            ["AutoCraftItems"] = Crafting,
            ["UseHealersHeart"] = Recharge,
            ["JumpOutWandCasting"] = Recharge | Spell,
            ["LootAllCorpses"] = Looting,
            ["LootFellowCorpses"] = Looting,
            ["DoJiggle"] = Spell,
            ["RandomHelperBuffs"] = Misc,
            ["RandomHelperIntervalSeconds"] = Misc,
            ["IdlePeaceMode"] = Misc,
            ["TargetLock"] = Combat,
            ["StopMacroOnDeath"] = Misc,
            ["UseArcs"] = Spell,
            ["ArcRange"] = Ranges | Spell,
            ["TargetSelectMethod"] = Combat,
            ["TargetSelectAngleRange"] = Ranges | Combat,
            ["IdleBuffTopoff"] = Buffing,
            ["IdleBuffTopoffTimeSeconds"] = Buffing,
            ["RebuffTimeRemainingSeconds"] = Buffing,
            ["RefillWornMana"] = Misc,
            ["RefillWornMana-Item-ManaPercent"] = Misc,
            ["BuffProfile-Prots"] = Buffing,
            ["BuffProfile-Banes"] = Buffing,
            ["BuffProfile_Prots"] = Buffing,
            ["BuffProfile_Banes"] = Buffing,
            ["DebuffEachFirst"] = Combat,
            ["AutoAttackPower"] = Melee,
            ["LootPriorityBoost"] = Looting,
            ["CorpseCacheTimeoutMinutes"] = Navigation,
            ["CorpseItemAppearanceTimeoutSeconds"] = Looting,
            ["CorpseItemIDTimeoutSeconds"] = Looting,
            ["DebuffSelectionMethod"] = Combat,
            ["ManaStoneLootCount"] = Misc | Looting,
            ["ManaTankMinimumMana"] = Misc | Looting,
            ["SplitPeas"] = Crafting,
            ["SpellCompMin-Critical"] = Crafting,
            ["SpellCompMin-Normal"] = Crafting,
            ["SpellCompMin-Idle"] = Crafting,
            ["RechargeBoostTimeSeconds"] = Recharge,
            ["RechargeBoostAmount"] = Recharge,
            ["UseSpecialAmmo"] = Crafting,
            ["OpenDoors"] = Navigation,
            ["DoorIDRange"] = Ranges | Navigation,
            ["DoorOpenRange"] = Ranges | Navigation,
            ["DoorLockpickDiffExcessThreshold"] = Navigation | Crafting,
            ["ManaChargesWhenOff"] = Misc,
            ["AutoFellowManagement"] = Misc,
            ["MinimumHealKitSuccessChance"] = Recharge,
            ["UseKitsInMagicMode"] = Recharge,
            ["StaminaToHealthMultiplier"] = Recharge,
            ["ManaToHealthMultiplier"] = Recharge,
            ["NavPriorityBoost"] = Navigation,
            ["DeleteGhostMonsters"] = Misc,
            ["GhostMonsterSpellAttemptCount"] = Misc,
            ["BlacklistMonsterAttemptCount"] = Misc,
            ["BlacklistMonsterTimeoutSeconds"] = Misc,
            ["CombineSalvage"] = Looting,
            ["LootOnlyRareCorpses"] = Looting,
            ["DeleteGhostMonstersByHPTracker"] = Misc | Combat,
            ["GhostDeleteHPTrackerSeconds"] = Misc | Combat,
            ["GoToPeaceModeToUseKits"] = Misc | Recharge,
            ["UseRecklessness"] = Melee,
            ["DebuffPrecastSeconds"] = Spell,
            ["ClearLevelBoostFlagOnCast"] = Recharge,
            ["IdleCraftCount_HealthKits"] = Recharge | Crafting,
            ["IdleCraftCount_StamKits"] = Recharge | Crafting,
            ["IdleCraftCount_ManaKits"] = Recharge | Crafting,
            ["IdleCraftCount_HealthFood"] = Recharge | Crafting,
            ["IdleCraftCount_StamFood"] = Recharge | Crafting,
            ["IdleCraftCount_ManaFood"] = Recharge | Crafting,
            ["BuffCastRecast_Seconds"] = Buffing,
            ["BuffCastRecastReset_Seconds"] = Buffing,
            ["EnableMeta"] = Misc,
            ["BlacklistedSpellComps"] = Recharge | Spell | Buffing,
            ["DropToPeaceModeRetryCount"] = Misc | Combat,
            ["FollowAroundCorners"] = Navigation,
            ["BlacklistCorpseOpenAttemptCount"] = Misc | Looting,
            ["BlacklistCorpseOpenTimeoutSeconds"] = Misc | Looting,
            ["SummonPets"] = Combat,
            ["PetRangeMode"] = Ranges | Combat,
            ["PetCustomRange"] = Ranges | Combat,
            ["PetRefillCount-Idle"] = Combat,
            ["PetRefillCount-Normal"] = Combat,
            ["CorpseOpenTimeoutSeconds"] = Looting,
            ["PetMonsterDensity"] = Combat,
            ["CorpseLootItemMaxAttempts"] = Looting,
            ["FastCastBuffs"] = Buffing,
            ["UseBreakableTurnTo"] = Spell,
            ["UseProjectileAwareness"] = Combat,
            ["CollisionProjectileRadius"] = Combat,
            ["CollisionStepDistance"] = Combat,
            ["ShowCollisionDebug"] = Combat,
            ["MaximumCollisionChecksPerTick"] = Combat,
            ["SpellRangeFudge"] = Spell,
            ["BuffWithUntrained-Item"] = Buffing,
            ["BuffWithUntrained-Creature"] = Buffing,
            ["BuffWithUntrained-Life"] = Buffing,
            ["AllowDebuffFallback"] = Combat,
        };

    /// <summary>What each setting does, in MossTank's words.</summary>
    internal static readonly IReadOnlyDictionary<string, string> Descriptions =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["EnableLooting"] = "Opens corpses and picks up what the loot profile keeps.",
            ["EnableNav"] = "Walks the loaded navigation route.",
            ["EnableBuffing"] = "Keeps the character's own buffs up.",
            ["EnableCombat"] = "Fights the monsters the monster rules pick.",
            ["SpellDiffExcessThreshold-Hunt"] = "Skill points a combat spell needs above its difficulty before it is cast.",
            ["SpellDiffExcessThreshold-Buff"] = "Skill points a buff needs above its difficulty before it is cast.",
            ["ArrowheadFletchDiffExcessThreshold"] = "Fletching points needed above a recipe's difficulty before arrowheads are made.",
            ["Recharge-Norm-HitP"] = "Health percent under which the character heals itself while fighting.",
            ["Recharge-Norm-Stam"] = "Stamina percent under which the character restores it while fighting.",
            ["Recharge-Norm-Mana"] = "Mana percent under which the character restores it while fighting.",
            ["Recharge-NoTarg-HitP"] = "Health percent the character tops up to when there is nothing to fight.",
            ["Recharge-NoTarg-Stam"] = "Stamina percent the character tops up to when there is nothing to fight.",
            ["Recharge-NoTarg-Mana"] = "Mana percent the character tops up to when there is nothing to fight.",
            ["Recharge-Helper-HitP"] = "Health percent under which another player is healed.",
            ["Recharge-Helper-Stam"] = "Stamina percent under which another player is given stamina.",
            ["Recharge-Helper-Mana"] = "Mana percent under which another player is given mana.",
            ["DoHelp"] = "Heals and restores stamina and mana for fellowship members and other allies nearby.",
            ["AttackDistance"] = "How far away a monster may be and still be attacked.",
            ["AttackMinimumDistance"] = "Monsters nearer than this are not attacked.",
            ["ApproachDistance"] = "How near the character walks to a monster it cannot hit from where it stands.",
            ["RingDistance"] = "How near monsters must be for a ring spell to count them.",
            ["CorpseApproachRange-Max"] = "How far away a corpse may be for the character to walk to it.",
            ["CorpseApproachRange-Min"] = "How near the character walks to a corpse before opening it.",
            ["NavCloseStopRange"] = "How near a route point counts as reached.",
            ["NavFarStopRange"] = "How far the character may stray from the route before the route stops.",
            ["UsePortalDistance"] = "How near a portal must be for a route step to use it.",
            ["HelperDistanceHitP"] = "How near another player must be to be healed.",
            ["HelperDistanceStam"] = "How near another player must be to be given stamina.",
            ["HelperDistanceMana"] = "How near another player must be to be given mana.",
            ["MinimumRingTargets"] = "How many monsters must be in ring range before a ring spell is cast.",
            ["DefaultMeleeAttackHeight"] = "The height melee attacks aim at when nothing else decides it.",
            ["CastDispelSelf"] = "Casts a self dispel when a vulnerability lands on the character.",
            ["UseDispelItems"] = "Uses a dispelling item when a vulnerability lands on the character.",
            ["AutoCram"] = "Moves items out of the main pack into side packs.",
            ["AutoStack"] = "Merges stacks of the same item.",
            ["ReadUnknownScrolls"] = "Picks up and reads scrolls of spells the character does not know yet (looting must be on).",
            ["UseDispelDrum"] = "Uses a dispelling drum when a vulnerability lands on the character.",
            ["SwitchWandsToDebuff"] = "Changes to the wand the monster rule names even for a debuff, not only for an attack.",
            ["AutoCraftItems"] = "Makes the consumables listed in the profile from their parts when none are left.",
            ["UseHealersHeart"] = "Uses a healer's heart from the item list to help others.",
            ["JumpOutWandCasting"] = "Jumps right after using a healer's heart, so its heal goes out at once.",
            ["LootAllCorpses"] = "Also loots corpses killed by players outside the fellowship.",
            ["LootFellowCorpses"] = "Also loots corpses killed by fellowship members.",
            ["DoJiggle"] = "Moves a little while casting, to throw off incoming spells.",
            ["RandomHelperBuffs"] = "Now and then casts a buff on a nearby player.",
            ["RandomHelperIntervalSeconds"] = "Seconds between buffs for nearby players.",
            ["IdlePeaceMode"] = "Stays in peace mode while looting, walking and salvaging.",
            ["TargetLock"] = "Attacks the selected monster first while it is a fair target.",
            ["StopMacroOnDeath"] = "Turns the macro off when the character dies.",
            ["UseArcs"] = "Whether arc spells are cast instead of bolts when both are known at the best level.",
            ["ArcRange"] = "How far away a monster may be for an arc to be chosen over a bolt.",
            ["TargetSelectMethod"] = "How the next monster is picked: by distance, by angle, or by angle when near and distance when far.",
            ["TargetSelectAngleRange"] = "Beyond this distance, picking by angle and distance switches to distance.",
            ["IdleBuffTopoff"] = "Recasts buffs while there is nothing else to do.",
            ["IdleBuffTopoffTimeSeconds"] = "Seconds of a buff left under which it is recast while idle.",
            ["RebuffTimeRemainingSeconds"] = "Seconds of a buff left under which it is recast.",
            ["RefillWornMana"] = "Refills worn items with the mana charges listed in the profile.",
            ["RefillWornMana-Item-ManaPercent"] = "Mana percent under which a worn item is refilled.",
            ["BuffProfile-Prots"] = "The protection elements cast when the protection choice is Custom.",
            ["BuffProfile-Banes"] = "The bane elements cast when the bane choice is Custom.",
            ["BuffProfile_Prots"] = "Which protection spells the character casts on itself.",
            ["BuffProfile_Banes"] = "Which bane spells the character casts on its armour.",
            ["DebuffEachFirst"] = "How much debuffing comes before the attack: one monster, every monster of the same priority, or every monster.",
            ["AutoAttackPower"] = "Sets the melee power bar to suit the weapon.",
            ["LootPriorityBoost"] = "Loots corpses before attacking the next monster.",
            ["CorpseCacheTimeoutMinutes"] = "Minutes a remembered corpse is kept before it is forgotten.",
            ["CorpseItemAppearanceTimeoutSeconds"] = "Seconds to wait for a corpse's items to appear.",
            ["CorpseItemIDTimeoutSeconds"] = "Seconds to wait for a corpse's items to be identified.",
            ["DebuffSelectionMethod"] = "What a debuff's source is chosen by: the spell's level or the caster's skill. Skill suits monsters with strong magic defence.",
            ["ManaStoneLootCount"] = "How many usable mana stones looting keeps in the pack.",
            ["ManaTankMinimumMana"] = "Mana an item must hold before it is drained into a mana stone.",
            ["SplitPeas"] = "Splits peas into spell components for the components the profile lists.",
            ["SpellCompMin-Critical"] = "Components of a kind under which a pea is split before anything else, healing included.",
            ["SpellCompMin-Normal"] = "Components of a kind under which a pea is split, after buffing.",
            ["SpellCompMin-Idle"] = "Components of a kind under which a pea is split while idle.",
            ["RechargeBoostTimeSeconds"] = "Seconds the recharge boost lasts after changing to magic mode to recharge.",
            ["RechargeBoostAmount"] = "Points of health, stamina or mana the recharge boost adds to the wish to recharge.",
            ["UseSpecialAmmo"] = "Which special ammunition may be made and used.",
            ["OpenDoors"] = "Opens closed doors along the route.",
            ["DoorIDRange"] = "How near a door must be to be identified.",
            ["DoorOpenRange"] = "How near a door must be to be opened.",
            ["DoorLockpickDiffExcessThreshold"] = "Lockpick points needed above a door's difficulty before it is picked.",
            ["ManaChargesWhenOff"] = "Keeps worn items filled with mana charges and stones even while the macro is off.",
            ["AutoFellowManagement"] = "Recruits players who ask and handles the waiting list and votes when leading a fellowship.",
            ["MinimumHealKitSuccessChance"] = "The lowest chance, in percent, of a healing kit working that is still worth using it.",
            ["UseKitsInMagicMode"] = "Uses healing kits in magic mode too, ahead of spells.",
            ["StaminaToHealthMultiplier"] = "How much better than a heal a stamina-to-health spell must be to be cast.",
            ["ManaToHealthMultiplier"] = "How much better than a heal a mana-to-health spell must be to be cast.",
            ["NavPriorityBoost"] = "Walks the route before attacking.",
            ["DeleteGhostMonsters"] = "Removes monsters the client still shows but that are not really there.",
            ["GhostMonsterSpellAttemptCount"] = "Spells that must fail to start on a monster before it counts as not there.",
            ["BlacklistMonsterAttemptCount"] = "Attacks that must miss a monster before it is left alone for a while.",
            ["BlacklistMonsterTimeoutSeconds"] = "Seconds a monster that cannot be hit is left alone.",
            ["CombineSalvage"] = "Combines salvage bags as the loot profile's ranges say (looting must be on).",
            ["LootOnlyRareCorpses"] = "Loots only corpses that can hold a rare.",
            ["DeleteGhostMonstersByHPTracker"] = "Also removes a monster whose health stops being reported, for every kind of attack.",
            ["GhostDeleteHPTrackerSeconds"] = "Seconds without a health report before a monster counts as not there.",
            ["GoToPeaceModeToUseKits"] = "Changes to peace mode before using a healing kit.",
            ["UseRecklessness"] = "Attacks with recklessness when the character has it.",
            ["DebuffPrecastSeconds"] = "Seconds before a debuff runs out that it is cast again (not for damage-over-time spells).",
            ["ClearLevelBoostFlagOnCast"] = "Lets the recharge boost count only for the first spell after changing to magic mode.",
            ["IdleCraftCount_HealthKits"] = "Health kits of each kind to make while idle.",
            ["IdleCraftCount_StamKits"] = "Stamina kits of each kind to make while idle.",
            ["IdleCraftCount_ManaKits"] = "Mana kits of each kind to make while idle.",
            ["IdleCraftCount_HealthFood"] = "Health food and potions of each kind to make while idle.",
            ["IdleCraftCount_StamFood"] = "Stamina food and potions of each kind to make while idle.",
            ["IdleCraftCount_ManaFood"] = "Mana food and potions of each kind to make while idle.",
            ["BuffCastRecast_Seconds"] = "After any buff is cast, every other buff is recast this many seconds earlier, for the reset time.",
            ["BuffCastRecastReset_Seconds"] = "Seconds the earlier recast lasts after a buff is cast.",
            ["EnableMeta"] = "Runs the loaded meta.",
            ["BlacklistedSpellComps"] = "Spell components never to cast with.",
            ["DropToPeaceModeRetryCount"] = "Tries at changing to peace mode to swap weapons before a wand is used instead.",
            ["FollowAroundCorners"] = "Follows the leader's path instead of running straight at where the leader is.",
            ["BlacklistCorpseOpenAttemptCount"] = "Tries at opening a corpse before it is left alone for a while.",
            ["BlacklistCorpseOpenTimeoutSeconds"] = "Seconds a corpse that will not open is left alone.",
            ["SummonPets"] = "Summons combat pets from the items the profile lists.",
            ["PetRangeMode"] = "Which distance counts monsters for summoning a pet: the attack distance or the pet's own.",
            ["PetCustomRange"] = "The pet's own distance for counting monsters.",
            ["PetRefillCount-Idle"] = "Charges left on a pet item under which it is refilled while idle.",
            ["PetRefillCount-Normal"] = "Charges left on a pet item under which it is refilled while fighting.",
            ["CorpseOpenTimeoutSeconds"] = "Seconds to wait for a corpse to open before trying again.",
            ["PetMonsterDensity"] = "Monsters that must be in pet range before a pet is summoned.",
            ["CorpseLootItemMaxAttempts"] = "Tries at picking up an item from a corpse before it is left behind.",
            ["FastCastBuffs"] = "Casts buffs quickly, which can move the character while casting.",
            ["UseBreakableTurnTo"] = "Lets something more urgent interrupt turning to face a spell's target.",
            ["UseProjectileAwareness"] = "Checks that an arc, bolt or arrow can reach its target before it is let go.",
            ["CollisionProjectileRadius"] = "The width of the test shape the reach check moves along the flight.",
            ["CollisionStepDistance"] = "How far the reach check moves its test shape at a time; keep it under twice the width.",
            ["ShowCollisionDebug"] = "Draws the reach check's test shape.",
            ["MaximumCollisionChecksPerTick"] = "The most monsters checked for reach in one pass.",
            ["SpellRangeFudge"] = "Meters taken off a spell's range to allow for positions not being exact.",
            ["BuffWithUntrained-Item"] = "Character level above which untrained Item Enchantment is not used to buff.",
            ["BuffWithUntrained-Creature"] = "Character level above which untrained Creature Enchantment is not used to buff.",
            ["BuffWithUntrained-Life"] = "Character level above which untrained Life Magic is not used to buff.",
            ["AllowDebuffFallback"] = "When a wall blocks a thrown debuff, uses one that does not fly instead.",
        };

    /// <summary>The label of each value a choice setting can take, in order.</summary>
    internal static readonly IReadOnlyList<(string Setting, int Value, string Label)> ChoiceLabels =
    [
        ("UseArcs", 1, "No"),
        ("UseArcs", 2, "At Range"),
        ("UseArcs", 3, "Yes"),
        ("TargetSelectMethod", 1, "By range"),
        ("TargetSelectMethod", 2, "By angle"),
        ("TargetSelectMethod", 3, "Both"),
        ("BuffProfile_Prots", 1, "Custom"),
        ("BuffProfile_Prots", 2, "All"),
        ("BuffProfile_Prots", 3, "None"),
        ("BuffProfile_Prots", 4, "B"),
        ("BuffProfile_Prots", 5, "BPS"),
        ("BuffProfile_Prots", 6, "BPSA"),
        ("BuffProfile_Prots", 7, "ALFC"),
        ("BuffProfile_Prots", 8, "BPSAC"),
        ("BuffProfile_Banes", 1, "Custom"),
        ("BuffProfile_Banes", 2, "All"),
        ("BuffProfile_Banes", 3, "None"),
        ("BuffProfile_Banes", 4, "B"),
        ("BuffProfile_Banes", 5, "BPS"),
        ("BuffProfile_Banes", 6, "BPSA"),
        ("BuffProfile_Banes", 7, "BPSAC"),
        ("BuffProfile_Banes", 8, "ALFC"),
        ("DebuffEachFirst", 1, "One"),
        ("DebuffEachFirst", 2, "Priority"),
        ("DebuffEachFirst", 3, "All"),
        ("DebuffSelectionMethod", 1, "SpellLevel"),
        ("DebuffSelectionMethod", 2, "Skill"),
        ("UseSpecialAmmo", 0, "None"),
        ("UseSpecialAmmo", 1, "Raider"),
        ("UseSpecialAmmo", 2, "SCurrency"),
        ("UseSpecialAmmo", 3, "Both"),
        ("PetRangeMode", 0, "AttackDistance"),
        ("PetRangeMode", 1, "PetCustomRange"),
    ];

    /// <summary>
    /// The recharge plan a new profile starts with: for each vital, stance
    /// and band of the vital, which way of restoring it is tried, in order.
    /// Vital 1 is health, 2 stamina, 3 mana; stance 1 is magic mode, 2 any other
    /// combat mode.
    /// </summary>
    internal static readonly IReadOnlyList<RechargeHandlerRow> DefaultRechargeHandlers =
    [
        new(1, "Stamina to Health", 0, 15, 1),
        new(1, "Mana to Health", 0, 15, 1),
        new(1, "Regular Spell", 0, 15, 1),
        new(1, "Recharge With Food", 0, 15, 1),
        new(1, "Kit Recharge", 0, 100, 1),
        new(1, "Stamina to Health", 0, 100, 1),
        new(1, "Mana to Health", 0, 100, 1),
        new(1, "Regular Spell", 0, 100, 1),
        new(1, "Recharge With Food", 0, 100, 1),
        new(2, "Kit Recharge", 0, 100, 1),
        new(2, "Regular Spell", 0, 100, 1),
        new(2, "Recharge With Food", 0, 100, 1),
        new(3, "Kit Recharge", 0, 100, 1),
        new(3, "Recharge With Food", 0, 100, 1),
        new(3, "Regular Spell", 0, 100, 1),
        new(1, "Recharge With Food", 0, 15, 2),
        new(1, "Kit Recharge", 0, 100, 2),
        new(1, "Recharge With Food", 0, 100, 2),
        new(1, "Stamina to Health", 0, 10, 2),
        new(1, "Regular Spell", 0, 100, 2),
        new(2, "Kit Recharge", 0, 100, 2),
        new(2, "Recharge With Food", 0, 100, 2),
        new(2, "Regular Spell", 0, 100, 2),
        new(3, "Kit Recharge", 0, 100, 2),
        new(3, "Recharge With Food", 0, 100, 2),
        new(3, "Regular Spell", 0, 100, 2),
    ];

    /// <summary>The gems a new profile uses for their buff: the two blessings anyone may carry.</summary>
    internal static readonly IReadOnlyList<GemFoodItem> DefaultGemFoodItems =
    [
        new("Asheron's Benediction", 3810u),
        new("Blackmoor's Favor", 3811u),
    ];
}
