<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <ItemGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <Compile Include="$(MSBuildThisFileDirectory)TestCultureInitializer.cs"
             Link="TestCultureInitializer.cs" />
  </ItemGroup>
</Project>
